# DustyCult July 1 Dippers

Run DustyCult quick fits for the July 1 review candidates labeled `dipper` in `output/runs/dat3-full-extended_2026-07-01-v4/review/review.db`.

This notebook writes fit metadata and posterior predictive curves back into the review DB tables used by the review app:

- `dustycult_fits`
- `dustycult_predictive_curves`
- `output/runs/dat3-full-extended_2026-07-01-v4/review/dustycult/<candidate>/quick/`

## Setup

Run these first. The fitting cells near the end are the only cells that intentionally update the review DB and DustyCult artifact directories.

In [1]:
from __future__ import annotations

import json
import math
import sqlite3
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.graph_objects as go
from IPython.display import Markdown, display

root_candidates = [Path.cwd(), *Path.cwd().parents]
REPO_ROOT = next(
    (
        p for p in root_candidates
        if (p / 'pyproject.toml').exists()
        and (p / 'malca' / 'review' / 'dustycult.py').exists()
    ),
    Path.cwd(),
)

for path in (REPO_ROOT, REPO_ROOT / 'malca'):
    text = str(path.resolve())
    if text not in sys.path:
        sys.path.insert(0, text)

from malca.io.notebook_paths import resolve_local_lightcurve_path
from malca.review.dustycult import (
    check_dustycult_available,
    control_defaults_for_candidate,
    load_dustycult_curve,
    load_dustycult_fits,
    run_dustycult_fit,
)
from malca.review.dustycult_display import (
    build_dustycult_fit_figure,
    dustycult_fit_metadata_rows,
    dustycult_geometry_rows,
    dustycult_posterior_rows,
    select_dustycult_display_row,
)
from malca.review.dustycult_visualization import build_dustycult_occulter_figure
from malca.review.store import db_connect

pd.set_option('display.max_columns', 180)
pd.set_option('display.max_rows', 160)
pd.set_option('display.width', 240)

/opt/homebrew/Caskroom/miniconda/base/envs/malca/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Configuration And Preflight

`MAX_CANDIDATES = 1` is the smoke-test default. The full-run cell below resets it to `None` and skips existing `ok` or `warning` quick fits.

In [2]:
RUN_DIR = REPO_ROOT / 'output' / 'runs' / 'dat3-full-extended_2026-07-01-v4'
DB_PATH = RUN_DIR / 'review' / 'review.db'
LIGHTCURVE_DIR = RUN_DIR / 'bundle_assets' / 'lightcurves'
PLOT_DIR = RUN_DIR / 'plots'
RESULTS_DIR = RUN_DIR / 'results'

MODES = ('quick',)
GOOD_STATUSES = {'ok', 'warning'}
RERUN_EXISTING = False
MAX_CANDIDATES = 1
EXPECTED_DIPPERS = 71
EXPECTED_MISSING_QUICK = 69
JULIA = 'julia'
DUSTYCULT_PROJECT = REPO_ROOT / 'external' / 'dustycult'
EXAMPLE_PLOT_MODE = 'quick'

RUN_PARAMS_PATH = RUN_DIR / 'run_params.json'
RUN_PARAMS = json.loads(RUN_PARAMS_PATH.read_text()) if RUN_PARAMS_PATH.exists() else {}

availability = check_dustycult_available(project_path=DUSTYCULT_PROJECT, julia=JULIA)

print(f'REPO_ROOT         = {REPO_ROOT}')
print(f'RUN_DIR           = {RUN_DIR}')
print(f'DB_PATH           = {DB_PATH}')
print(f'LIGHTCURVE_DIR    = {LIGHTCURVE_DIR}')
print(f'PLOT_DIR          = {PLOT_DIR}')
print(f'DUSTYCULT_PROJECT = {DUSTYCULT_PROJECT}')
print(f'DB exists         = {DB_PATH.exists()}')
print(f'LC dir exists     = {LIGHTCURVE_DIR.is_dir()}')
print(f'run_params exists = {RUN_PARAMS_PATH.exists()}')
print(f'Julia executable  = {availability.julia}')
print(f'DustyCult status  = {availability.message}')

if not DB_PATH.exists():
    raise FileNotFoundError(DB_PATH)
if not LIGHTCURVE_DIR.is_dir():
    raise FileNotFoundError(LIGHTCURVE_DIR)
if not availability.ok:
    raise RuntimeError(availability.message)

REPO_ROOT         = /Users/calder/code/malca
RUN_DIR           = /Users/calder/code/malca/output/runs/dat3-full-extended_2026-07-01-v4
DB_PATH           = /Users/calder/code/malca/output/runs/dat3-full-extended_2026-07-01-v4/review/review.db
LIGHTCURVE_DIR    = /Users/calder/code/malca/output/runs/dat3-full-extended_2026-07-01-v4/bundle_assets/lightcurves
PLOT_DIR          = /Users/calder/code/malca/output/runs/dat3-full-extended_2026-07-01-v4/plots
DUSTYCULT_PROJECT = /Users/calder/code/malca/external/dustycult
DB exists         = True
LC dir exists     = True
run_params exists = True
Julia executable  = julia
DustyCult status  = DustyCult is available

## Load July 1 Dipper Candidates

This uses the strict selector `reviews.event_class = 'dipper'`.

In [3]:
DIPPER_WHERE = "r.event_class = 'dipper'"

with db_connect(DB_PATH) as conn:
    reviewed_dippers = pd.read_sql_query(
        f'''
        SELECT
            c.*,
            r.event_class,
            r.workflow_status,
            r.disposition,
            r.morphology_primary,
            r.morphology_secondary,
            r.morphology_secondary_json,
            r.physical_primary,
            r.physical_secondary,
            r.classification_confidence,
            r.priority_tags_json,
            r.notes AS review_notes,
            r.updated_at AS review_updated_at
        FROM reviews r
        JOIN candidates c USING(candidate_id)
        WHERE {DIPPER_WHERE}
        ORDER BY r.updated_at DESC, r.candidate_id
        ''',
        conn,
    )
    existing_fits = pd.read_sql_query(
        f'''
        SELECT candidate_id, mode, status, updated_at, runtime_sec, t0_jd, start_jd, end_jd,
               n_input_points, n_curve_points, artifact_dir, error
        FROM dustycult_fits
        WHERE candidate_id IN (
            SELECT r.candidate_id FROM reviews r WHERE {DIPPER_WHERE}
        )
        ORDER BY candidate_id, mode
        ''',
        conn,
    )

quick_fits = existing_fits[existing_fits['mode'].astype(str).eq('quick')].copy() if not existing_fits.empty else pd.DataFrame()
good_quick_ids = set(
    quick_fits.loc[quick_fits['status'].astype(str).isin(GOOD_STATUSES), 'candidate_id'].astype(str)
) if not quick_fits.empty else set()
missing_quick_count = int(len(reviewed_dippers) - len(good_quick_ids))

print(f'July 1 dippers: {len(reviewed_dippers)}')
print(f'Existing quick fits with ok/warning status: {len(good_quick_ids)}')
print(f'Missing quick fits by skip policy: {missing_quick_count}')

if len(reviewed_dippers) != EXPECTED_DIPPERS:
    display(Markdown(f'**Warning:** expected `{EXPECTED_DIPPERS}` dippers, found `{len(reviewed_dippers)}`.'))
if missing_quick_count != EXPECTED_MISSING_QUICK:
    display(Markdown(f'**Warning:** expected `{EXPECTED_MISSING_QUICK}` missing quick fits, found `{missing_quick_count}`.'))

display_cols = [
    'candidate_id', 'event_class', 'workflow_status', 'disposition',
    'morphology_primary', 'morphology_secondary', 'physical_primary',
    'dipper_score', 'dipper_n_valid_dips', 'dip_run_count', 'dip_best_morph',
]
display(reviewed_dippers[[col for col in display_cols if col in reviewed_dippers.columns]])
display(existing_fits if not existing_fits.empty else Markdown('No existing DustyCult fits for these dippers.'))

July 1 dippers: 71
Existing quick fits with ok/warning status: 2
Missing quick fits by skip policy: 69

        candidate_id event_class workflow_status disposition morphology_primary   morphology_secondary                     physical_primary  dipper_score  dipper_n_valid_dips  dip_run_count dip_best_morph
0   stv_360777826205      dipper        reviewed        keep      dimming_event             big_dipper                                 None     21.400308                 67.0            4.0          noise
1   stv_197569226514      dipper        reviewed        keep      dimming_event         asymmetric_dip                                 None     -1.597394                 11.0            6.0          noise
2   stv_395138016907      dipper        reviewed        keep      dimming_event             single_dip                                 None     20.315220                 58.0           15.0       gaussian
3   stv_163209415214      dipper        reviewed        keep      dimming_event              sharp_dip                                 None     18.589905                 20.0            6.0  skew_gaussian
4   stv_403727411589      dipper        reviewed        keep      dimming_event             single_dip                                 None     18.884118                 37.0            4.0       gaussian
5    stv_25770316308      dipper        reviewed        keep      dimming_event    quasi_periodic_dips                                 None     20.531731                 23.0            1.0       gaussian
6   stv_584116028406      dipper        reviewed        keep      dimming_event             single_dip                                 None     -0.523791                  9.0            4.0       gaussian
7   stv_154620038181      dipper        reviewed        keep      dimming_event              sharp_dip                                 None     18.878795                 28.0           12.0       gaussian
8   stv_180388640882      dipper        reviewed        keep      dimming_event              sharp_dip                                 None     21.756072                 40.0            3.0       gaussian
9    stv_17181027305      dipper        reviewed        keep      dimming_event             single_dip                                 None     -3.302735                  4.0            1.0       gaussian
10  stv_592705538522      dipper        reviewed        keep      dimming_event              broad_dip                                 None     15.250353                 33.0            5.0       gaussian
11  stv_601295761416      dipper        reviewed        keep      dimming_event             single_dip                                 None     14.155961                  7.0            5.0  skew_gaussian
12  stv_111669273145      dipper        reviewed        keep      dimming_event         recurrent_dips                                 None     -1.061881                 12.0            1.0          noise
13  stv_395137575008      dipper        reviewed        keep      dimming_event              sharp_dip                                 None     19.855731                 14.0            4.0       gaussian
14   stv_60130141761      dipper        reviewed        keep      dimming_event              broad_dip                                 None     -2.200192                  5.0            2.0       gaussian
15   stv_68720714610      dipper        reviewed        keep      dimming_event             single_dip                                 None     22.593899                  7.0            1.0       gaussian
16  stv_541166985810      dipper        reviewed        keep      dimming_event             single_dip                                 None     14.687755                 19.0            2.0       gaussian
17  stv_300648087617      dipper        reviewed        keep      dimming_event              broad_dip                                 None     -1.150219                 11.0            4.0       gaussian
18  stv_541166181486      dipper        reviewed        keep      dimming_event             single_dip                                 None     -1.678742                 18.0            3.0  skew_gaussian
19  stv_644245359876      dipper        reviewed        keep      dimming_event              broad_dip                                 None     20.097943                 28.0           12.0       gaussian
20  stv_446677131304      dipper        reviewed        keep      dimming_event             single_dip                                 None     21.049274                 27.0           12.0       gaussian
21  stv_566936751170      dipper        reviewed        keep      dimming_event             single_dip                                 None     21.099749                 25.0           17.0       gaussian
22  stv_197569238413      dipper        reviewed        keep      dimming_event             single_dip                                 None     -1.750690                 13.0            2.0       gaussian
23  stv_566936725849      dipper        reviewed        keep      dimming_event             single_dip                                 None     12.964988                 11.0            3.0       gaussian
24  stv_369367304600      dipper        reviewed        keep      dimming_event             single_dip                                 None     -0.876739                  2.0            4.0       gaussian
25  stv_266288257407      dipper        reviewed        keep      dimming_event             single_dip                                 None     -0.801448                 25.0            9.0  skew_gaussian
26  stv_609885850038      dipper        reviewed        keep      dimming_event              broad_dip                                 None      1.164025                  4.0            2.0       gaussian
27  stv_240518717560      dipper        reviewed        keep      dimming_event             single_dip                                 None     17.854329                  9.0            3.0       gaussian
28  stv_472446832201      dipper        reviewed        keep      dimming_event             single_dip                                 None     -1.745075                  7.0            6.0       gaussian
29  stv_369368258528      dipper        reviewed        keep      dimming_event         asymmetric_dip                                 None     -0.485853                 13.0            2.0       gaussian
30  stv_627065319105      dipper        reviewed        keep      dimming_event             big_dipper                                 None     -0.398252                 65.0           28.0       gaussian
31  stv_489626538045      dipper        reviewed        keep      dimming_event             single_dip                                 None     20.511057                 15.0            6.0       gaussian
32   stv_94489594805      dipper        reviewed        keep      dimming_event             single_dip                                 None      0.796382                  1.0            1.0       gaussian
33  stv_446677119900      dipper        reviewed        keep      dimming_event              sharp_dip                                 None     19.230820                 56.0           10.0       gaussian
34  stv_523987067704      dipper        reviewed        keep      dimming_event         recurrent_dips                                 None      0.221111                 34.0            4.0  skew_gaussian
35   stv_42950519514      dipper        reviewed        keep      dimming_event          symmetric_dip                                 None      0.459266                  2.0            3.0       gaussian
36  stv_601295730966      dipper        reviewed        keep      dimming_event         asymmetric_dip                                 None     14.126181                  2.0            2.0       gaussian
37  stv_283467842509      dipper        reviewed        keep      dimming_event              sharp_dip                                 None     22.089526                 15.0            7.0       gaussian
38  stv_532576256705      dipper        reviewed        keep      dimming_event         asymmetric_dip                                 None     -1.245946                  2.0            3.0       gaussian
39  stv_249109213616      dipper        reviewed        keep      dimming_event             single_dip                                 None     -1.037036                 10.0            5.0       gaussian
40  stv_283468165807      dipper        reviewed        keep      dimming_event             single_dip                                 None     -2.683195                  2.0            4.0       gaussian
41  stv_420907788679      dipper        reviewed        keep      dimming_event             single_dip                                 None     19.825896                 33.0            3.0       gaussian
42   stv_94489437356      dipper        reviewed        keep      dimming_event             big_dipper                                 None     13.393570                  3.0            2.0       gaussian
43  stv_489626566903      dipper        reviewed        keep      dimming_event        stochastic_dips                                 None      0.455536                 19.0            2.0       gaussian
44  stv_128850429575      dipper        reviewed        keep      dimming_event         recurrent_dips                                 None     -0.239391                 10.0            3.0       gaussian
45  stv_240519504803      dipper        reviewed        keep      dimming_event         aperiodic_dips                                 None     20.419032                 52.0            7.0       gaussian
46   stv_68719676517      dipper        reviewed        keep      dimming_event             single_dip  dust_obscuration_or_fading_variable     -1.729910                  1.0            1.0       gaussian
47  stv_163209590869      dipper        reviewed        keep      dimming_event        secular_dimming                              unknown     16.294778                 26.0            8.0  skew_gaussian
48  stv_481036839646      dipper        reviewed        keep      dimming_event         recurrent_dips                              unknown      1.966557                 21.0            5.0  skew_gaussian
49  stv_463857647562      dipper        reviewed        keep      dimming_event       multi_depth_dips                              unknown     17.609375                  8.0            4.0       gaussian
50  stv_300648890329      dipper        reviewed        keep      dimming_event         recurrent_dips                              unknown     22.010603                  9.0            2.0       gaussian
51  stv_111669291649      dipper        reviewed        keep      dimming_event         recurrent_dips                              unknown     -0.494195                 21.0            3.0       gaussian
52  stv_498216222923      dipper        reviewed        keep      dimming_event                   None                                 None     -1.073398                  2.0            2.0       gaussian
53  stv_240518636016      dipper        reviewed        keep      dimming_event       multi_depth_dips                                 None     20.345949                 47.0           15.0       gaussian
54  stv_446676921101      dipper        reviewed        keep      dimming_event                   None                                 None     -1.583966                  5.0            1.0       gaussian
55  stv_549755992463      dipper        reviewed        keep      dimming_event  dimming_with_recovery          young_stellar_object_or_pms     -1.744238                  5.0            1.0       gaussian
56  stv_223338997633      dipper        reviewed        keep      dimming_event                   None                                 None     21.150434                 24.0            7.0  skew_gaussian
57    stv_8591303502      dipper        reviewed        keep      dimming_event                   None                                 None     18.645683                  9.0            1.0       gaussian
58  stv_523986354332      dipper        reviewed        keep      dimming_event                   None                                 None      0.917497                 26.0            3.0       gaussian
59   stv_25771086021      dipper        reviewed        keep      dimming_event                   None                                 None     14.432371                 17.0            2.0       gaussian
60  stv_481036586933      dipper        reviewed        keep      dimming_event                   None                                 None     -0.880867                 29.0            3.0       gaussian
61  stv_532576054353      dipper        reviewed        keep      dimming_event                   None                                 None     18.791993                 36.0            3.0  skew_gaussian
62  stv_592705518006      dipper        reviewed        keep      dimming_event                   None                                 None     20.915310                 43.0            3.0       gaussian
63  stv_146029419304      dipper        reviewed        keep      dimming_event                   None                                 None     20.054809                 32.0            3.0       gaussian
64  stv_369367489518      dipper        reviewed        keep      dimming_event                   None                                 None     21.781662                 40.0            9.0       gaussian
65  stv_515396131751      dipper        reviewed        keep      dimming_event                   None                                 None     21.487371                 36.0            7.0       gaussian
66  stv_206158525635      dipper        reviewed        keep      dimming_event                   None                                 None     20.370228                 70.0           16.0       gaussian
67  stv_111669557747      dipper        reviewed        keep      dimming_event                   None                                 None     13.847221                  5.0            2.0          noise
68  stv_644245286164      dipper        reviewed        keep      dimming_event                   None                                 None     19.061799                 72.0            1.0       gaussian
69   stv_94489786439      dipper        reviewed        keep      dimming_event                   None                                 None     16.292546                 12.0            5.0       gaussian
70  stv_180388903123      dipper        reviewed        keep      dimming_event                   None                                 None     -1.230610                  2.0            1.0       gaussian

,candidate_id,mode,status,updated_at,runtime_sec,t0_jd,start_jd,end_jd,n_input_points,n_curve_points,artifact_dir,error
0,stv_369367304600,quick,ok,2026-07-09T05:52:31.639486+00:00,16.276035,2.460712e+06,2.460704e+06,2.460725e+06,4,4,/Users/calder/code/malca/output/runs/dat3-full...,
1,stv_566936725849,quick,warning,2026-07-09T07:36:59.650249+00:00,2304.978950,2.460070e+06,2.460003e+06,2.460137e+06,76,76,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...

## Helpers

These mirror the review app path resolution and DustyCult fit calls, but keep execution serial for DB safety.

In [4]:
def _finite_float(value, default=None):
    try:
        if value is None or pd.isna(value):
            return default
    except Exception:
        if value is None:
            return default
    try:
        number = float(value)
    except (TypeError, ValueError):
        return default
    return number if math.isfinite(number) else default


def clean_value(value):
    try:
        if pd.isna(value):
            return None
    except Exception:
        pass
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating,)):
        return float(value)
    return value


def row_payload(row: pd.Series) -> dict[str, object]:
    payload: dict[str, object] = {}
    raw = row.get('payload_json')
    if isinstance(raw, str) and raw.strip():
        try:
            payload.update(json.loads(raw))
        except Exception:
            pass
    for key, value in row.items():
        cleaned = clean_value(value)
        if cleaned is not None:
            payload[key] = cleaned
    payload['candidate_id'] = str(row['candidate_id'])
    return payload


def resolve_candidate_lc_path(row: pd.Series, payload: dict[str, object] | None = None) -> Path | None:
    payload = payload or row_payload(row)
    candidates = [
        row.get('lc_path'),
        payload.get('lc_path'),
        payload.get('path'),
        payload.get('dat_path'),
        payload.get('asas_sn_id'),
        row.get('candidate_id'),
    ]
    for value in candidates:
        if value is None:
            continue
        resolved = resolve_local_lightcurve_path(value, run_dir=RUN_DIR, repo_root=REPO_ROOT)
        if resolved is not None and resolved.exists():
            return resolved
    return None


def mode_status(fits: pd.DataFrame, candidate_id: str, mode: str) -> str | None:
    if fits.empty:
        return None
    sub = fits[(fits['candidate_id'].astype(str) == str(candidate_id)) & (fits['mode'].astype(str) == str(mode))]
    if sub.empty:
        return None
    if 'updated_at' in sub.columns:
        sub = sub.sort_values('updated_at')
    return str(sub.iloc[-1].get('status') or '') or None


def planned_mode_action(fits: pd.DataFrame, candidate_id: str, mode: str) -> str:
    status = mode_status(fits, candidate_id, mode)
    if RERUN_EXISTING:
        return 'rerun_existing'
    if status in GOOD_STATUSES:
        return 'skipped_existing_good'
    if status:
        return f'retry_existing_{status}'
    return 'run_missing'


def active_controls_for_candidate(
    conn: sqlite3.Connection,
    candidate_id: str,
    payload: dict[str, object],
    *,
    lc_path: Path | None,
) -> dict[str, object]:
    defaults = control_defaults_for_candidate(
        conn,
        candidate_id,
        payload,
        lc_path=lc_path,
        plot_dir=PLOT_DIR,
        run_params=RUN_PARAMS,
        recompute=False,
    )
    controls = {key: defaults.get(key) for key in defaults.keys()}
    controls['_dustycult_window_source'] = str(defaults.get('source') or 'defaults')
    return controls


def select_fit_candidates(max_candidates: int | None = None) -> pd.DataFrame:
    data = reviewed_dippers.copy()
    if max_candidates is not None:
        data = data.head(int(max_candidates)).copy()
    return data.reset_index(drop=True)


def reload_existing_fits(candidate_ids: list[str] | None = None) -> pd.DataFrame:
    ids = [str(item) for item in (candidate_ids or reviewed_dippers['candidate_id'].astype(str).tolist())]
    if not ids:
        return pd.DataFrame()
    placeholders = ','.join(['?'] * len(ids))
    with db_connect(DB_PATH) as conn:
        return pd.read_sql_query(
            f'''
            SELECT candidate_id, mode, status, updated_at, runtime_sec, t0_jd, start_jd, end_jd,
                   n_input_points, n_curve_points, artifact_dir, error
            FROM dustycult_fits
            WHERE candidate_id IN ({placeholders})
            ORDER BY candidate_id, mode
            ''',
            conn,
            params=ids,
        )


def build_dry_run_queue(max_candidates: int | None = None) -> pd.DataFrame:
    fit_candidates = select_fit_candidates(max_candidates)
    current_fits = reload_existing_fits(fit_candidates['candidate_id'].astype(str).tolist())
    rows = []
    with db_connect(DB_PATH) as conn:
        for _, row in fit_candidates.iterrows():
            candidate_id = str(row['candidate_id'])
            payload = row_payload(row)
            lc_path = resolve_candidate_lc_path(row, payload)
            controls = active_controls_for_candidate(conn, candidate_id, payload, lc_path=lc_path)
            quick_status = mode_status(current_fits, candidate_id, 'quick')
            rows.append(
                {
                    'candidate_id': candidate_id,
                    'lc_found': lc_path is not None,
                    'lc_path': str(lc_path) if lc_path else '',
                    'quick_status': quick_status or 'missing',
                    'quick_action': planned_mode_action(current_fits, candidate_id, 'quick'),
                    'window_source': controls.get('_dustycult_window_source'),
                    'start_jd': controls.get('start_jd'),
                    't0_jd': controls.get('t0_jd'),
                    'end_jd': controls.get('end_jd'),
                    'dipper_score': row.get('dipper_score'),
                    'dipper_n_valid_dips': row.get('dipper_n_valid_dips'),
                    'dip_run_count': row.get('dip_run_count'),
                    'dip_best_morph': row.get('dip_best_morph'),
                }
            )
    return pd.DataFrame(rows)

## Dry-Run Queue

This cell does not write anything. Use it before the smoke test and again before the full run.

In [5]:
dry_run_queue = build_dry_run_queue(max_candidates=None)
display(dry_run_queue)
display(dry_run_queue.groupby(['quick_action', 'lc_found'], dropna=False).size().reset_index(name='n'))

OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.

,candidate_id,lc_found,lc_path,quick_status,quick_action,window_source,start_jd,t0_jd,end_jd,dipper_score,dipper_n_valid_dips,dip_run_count,dip_best_morph
0,stv_360777826205,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,recomputed_dip_run,2.458413e+06,2.458414e+06,2.458415e+06,21.400308,67.0,4.0,noise
1,stv_197569226514,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,recomputed_dip_run,2.459297e+06,2.459224e+06,2.459346e+06,-1.597394,11.0,6.0,noise
2,stv_395138016907,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.458081e+06,2.458201e+06,2.458321e+06,20.315220,58.0,15.0,gaussian
3,stv_163209415214,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,recomputed_dip_run,2.460378e+06,2.460375e+06,2.460398e+06,18.589905,20.0,6.0,skew_gaussian
4,stv_403727411589,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.458084e+06,2.458204e+06,2.458324e+06,18.884118,37.0,4.0,gaussian
5,stv_25770316308,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,recompute_deepest_point_fallback,2.458778e+06,2.458785e+06,2.458792e+06,20.531731,23.0,1.0,gaussian
6,stv_584116028406,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.460884e+06,2.460936e+06,2.460988e+06,-0.523791,9.0,4.0,gaussian
7,stv_154620038181,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.459738e+06,2.459812e+06,2.459885e+06,18.878795,28.0,12.0,gaussian
8,stv_180388640882,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.460384e+06,2.460504e+06,2.460624e+06,21.756072,40.0,3.0,gaussian
9,stv_17181027305,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,recompute_deepest_point_fallback,2.460317e+06,2.460324e+06,2.460331e+06,-3.302735,4.0,1.0,gaussian
10,stv_592705538522,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.460798e+06,2.460918e+06,2.461038e+06,15.250353,33.0,5.0,gaussian
11,stv_601295761416,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.458462e+06,2.458558e+06,2.458654e+06,14.155961,7.0,5.0,skew_gaussian
12,stv_111669273145,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,recomputed_dip_run,2.460269e+06,2.460276e+06,2.460280e+06,-1.061881,12.0,1.0,noise
13,stv_395137575008,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.458307e+06,2.458394e+06,2.458481e+06,19.855731,14.0,4.0,gaussian
14,stv_60130141761,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.458335e+06,2.458455e+06,2.458575e+06,-2.200192,5.0,2.0,gaussian
15,stv_68720714610,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.458313e+06,2.458433e+06,2.458553e+06,22.593899,7.0,1.0,gaussian
16,stv_541166985810,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.459893e+06,2.460013e+06,2.460133e+06,14.687755,19.0,2.0,gaussian
17,stv_300648087617,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.458452e+06,2.458459e+06,2.458466e+06,-1.150219,11.0,4.0,gaussian
18,stv_541166181486,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.460391e+06,2.460511e+06,2.460631e+06,-1.678742,18.0,3.0,skew_gaussian
19,stv_644245359876,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.458757e+06,2.458877e+06,2.458997e+06,20.097943,28.0,12.0,gaussian
20,stv_446677131304,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.458525e+06,2.458548e+06,2.458570e+06,21.049274,27.0,12.0,gaussian
21,stv_566936751170,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,recompute_deepest_point_fallback,2.460073e+06,2.460080e+06,2.460087e+06,21.099749,25.0,17.0,gaussian
22,stv_197569238413,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,recomputed_dip_run,2.458467e+06,2.458467e+06,2.458468e+06,-1.750690,13.0,2.0,gaussian
23,stv_566936725849,True,/Users/calder/code/malca/output/runs/dat3-full...,warning,skipped_existing_good,stored_event_columns,2.460003e+06,2.460070e+06,2.460137e+06,12.964988,11.0,3.0,gaussian
24,stv_369367304600,True,/Users/calder/code/malca/output/runs/dat3-full...,ok,skipped_existing_good,stored_event_columns,2.460643e+06,2.460763e+06,2.460883e+06,-0.876739,2.0,4.0,gaussian
25,stv_266288257407,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,recomputed_dip_run,2.457848e+06,2.457809e+06,2.457891e+06,-0.801448,25.0,9.0,skew_gaussian
26,stv_609885850038,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.460623e+06,2.460743e+06,2.460863e+06,1.164025,4.0,2.0,gaussian
27,stv_240518717560,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.458700e+06,2.458820e+06,2.458940e+06,17.854329,9.0,3.0,gaussian
28,stv_472446832201,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.459717e+06,2.459837e+06,2.459957e+06,-1.745075,7.0,6.0,gaussian
29,stv_369368258528,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.460153e+06,2.460273e+06,2.460393e+06,-0.485853,13.0,2.0,gaussian
30,stv_627065319105,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.460633e+06,2.460753e+06,2.460873e+06,-0.398252,65.0,28.0,gaussian
31,stv_489626538045,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.460072e+06,2.460192e+06,2.460312e+06,20.511057,15.0,6.0,gaussian
32,stv_94489594805,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.458266e+06,2.458386e+06,2.458506e+06,0.796382,1.0,1.0,gaussian
33,stv_446677119900,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.459597e+06,2.459617e+06,2.459637e+06,19.230820,56.0,10.0,gaussian
34,stv_523987067704,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.457426e+06,2.457546e+06,2.457666e+06,0.221111,34.0,4.0,skew_gaussian
35,stv_42950519514,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.459165e+06,2.459285e+06,2.459405e+06,0.459266,2.0,3.0,gaussian
36,stv_601295730966,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.459651e+06,2.459771e+06,2.459891e+06,14.126181,2.0,2.0,gaussian
37,stv_283467842509,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.460826e+06,2.460846e+06,2.460867e+06,22.089526,15.0,7.0,gaussian
38,stv_532576256705,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.458401e+06,2.458521e+06,2.458641e+06,-1.245946,2.0,3.0,gaussian
39,stv_249109213616,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.460224e+06,2.460344e+06,2.460464e+06,-1.037036,10.0,5.0,gaussian
40,stv_283468165807,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.458110e+06,2.458230e+06,2.458350e+06,-2.683195,2.0,4.0,gaussian
41,stv_420907788679,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.460504e+06,2.460614e+06,2.460724e+06,19.825896,33.0,3.0,gaussian
42,stv_94489437356,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.460784e+06,2.460904e+06,2.461024e+06,13.393570,3.0,2.0,gaussian
43,stv_489626566903,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.458743e+06,2.458863e+06,2.458983e+06,0.455536,19.0,2.0,gaussian
44,stv_128850429575,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.457384e+06,2.457504e+06,2.457624e+06,-0.239391,10.0,3.0,gaussian
45,stv_240519504803,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.458290e+06,2.458337e+06,2.458385e+06,20.419032,52.0,7.0,gaussian
46,stv_68719676517,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.460667e+06,2.460787e+06,2.460907e+06,-1.729910,1.0,1.0,gaussian
47,stv_163209590869,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.459387e+06,2.459435e+06,2.459482e+06,16.294778,26.0,8.0,skew_gaussian
48,stv_481036839646,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.457977e+06,2.458097e+06,2.458217e+06,1.966557,21.0,5.0,skew_gaussian
49,stv_463857647562,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.460369e+06,2.460489e+06,2.460609e+06,17.609375,8.0,4.0,gaussian
50,stv_300648890329,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.457379e+06,2.457499e+06,2.457619e+06,22.010603,9.0,2.0,gaussian
51,stv_111669291649,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.457252e+06,2.457349e+06,2.457447e+06,-0.494195,21.0,3.0,gaussian
52,stv_498216222923,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,recomputed_dip_run,2.458900e+06,2.458983e+06,2.458926e+06,-1.073398,2.0,2.0,gaussian
53,stv_240518636016,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.457600e+06,2.457656e+06,2.457713e+06,20.345949,47.0,15.0,gaussian
54,stv_446676921101,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.458819e+06,2.458900e+06,2.458980e+06,-1.583966,5.0,1.0,gaussian
55,stv_549755992463,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.459985e+06,2.460020e+06,2.460055e+06,-1.744238,5.0,1.0,gaussian
56,stv_223338997633,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.460428e+06,2.460548e+06,2.460668e+06,21.150434,24.0,7.0,skew_gaussian
57,stv_8591303502,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.458229e+06,2.458328e+06,2.458427e+06,18.645683,9.0,1.0,gaussian
58,stv_523986354332,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,recomputed_dip_run,2.460220e+06,2.460773e+06,2.460589e+06,0.917497,26.0,3.0,gaussian
59,stv_25771086021,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.458690e+06,2.458810e+06,2.458930e+06,14.432371,17.0,2.0,gaussian
60,stv_481036586933,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,recompute_deepest_point_fallback,2.458922e+06,2.458929e+06,2.458936e+06,-0.880867,29.0,3.0,gaussian
61,stv_532576054353,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.458747e+06,2.458770e+06,2.458793e+06,18.791993,36.0,3.0,skew_gaussian
62,stv_592705518006,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,recompute_deepest_point_fallback,2.459745e+06,2.459752e+06,2.459759e+06,20.915310,43.0,3.0,gaussian
63,stv_146029419304,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,recompute_deepest_point_fallback,2.458313e+06,2.458320e+06,2.458327e+06,20.054809,32.0,3.0,gaussian
64,stv_369367489518,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.459390e+06,2.459429e+06,2.459469e+06,21.781662,40.0,9.0,gaussian
65,stv_515396131751,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.459928e+06,2.459992e+06,2.460056e+06,21.487371,36.0,7.0,gaussian
66,stv_206158525635,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,stored_event_columns,2.458321e+06,2.458348e+06,2.458375e+06,20.370228,70.0,16.0,gaussian
67,stv_111669557747,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,recomputed_dip_run,2.458297e+06,2.458325e+06,2.458353e+06,13.847221,5.0,2.0,noise
68,stv_644245286164,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,recompute_deepest_point_fallback,2.460123e+06,2.460130e+06,2.460137e+06,19.061799,72.0,1.0,gaussian
69,stv_94489786439,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,recomputed_dip_run,2.458507e+06,2.458516e+06,2.458508e+06,16.292546,12.0,5.0,gaussian
70,stv_180388903123,True,/Users/calder/code/malca/output/runs/dat3-full...,missing,run_missing,recomputed_dip_run,2.458536e+06,2.458757e+06,2.458595e+06,-1.230610,2.0,1.0,gaussian

            quick_action  lc_found   n
0            run_missing      True  69
1  skipped_existing_good      True   2

## Run DustyCult Fits

These cells write to the review DB and create/recreate DustyCult artifacts for candidates that are not skipped.

In [6]:
def record_result(results: list[dict[str, object]], candidate_id: str, mode: str, action: str, row: dict[str, object] | None = None, error: str = '') -> None:
    row = dict(row or {})
    results.append(
        {
            'candidate_id': str(candidate_id),
            'mode': mode,
            'action': action,
            'status': row.get('status', ''),
            'runtime_sec': row.get('runtime_sec'),
            't0_jd': row.get('t0_jd'),
            'start_jd': row.get('start_jd'),
            'end_jd': row.get('end_jd'),
            'n_input_points': row.get('n_input_points'),
            'n_curve_points': row.get('n_curve_points'),
            'artifact_dir': row.get('artifact_dir', ''),
            'error': row.get('error', error),
        }
    )


def run_fit_queue(max_candidates: int | None = None) -> pd.DataFrame:
    fit_candidates = select_fit_candidates(max_candidates)
    results: list[dict[str, object]] = []
    started = time.monotonic()

    with db_connect(DB_PATH) as conn:
        for idx, row in fit_candidates.iterrows():
            candidate_id = str(row['candidate_id'])
            payload = row_payload(row)
            lc_path = resolve_candidate_lc_path(row, payload)
            if lc_path is not None:
                payload['lc_path'] = str(lc_path)

            print(f'[{idx + 1}/{len(fit_candidates)}] {candidate_id}')
            fits_before = load_dustycult_fits(conn, candidate_id)
            controls = active_controls_for_candidate(conn, candidate_id, payload, lc_path=lc_path)

            quick_action = planned_mode_action(fits_before, candidate_id, 'quick')
            if quick_action == 'skipped_existing_good':
                status = mode_status(fits_before, candidate_id, 'quick') or 'skipped'
                record_result(results, candidate_id, 'quick', quick_action, {'status': status, **controls})
                print(f'  quick: skipped existing {status}')
                continue

            quick_row = run_dustycult_fit(
                conn,
                candidate_id,
                payload,
                db_path=DB_PATH,
                controls=controls,
                mode='quick',
                lc_path=lc_path,
                plot_dir=PLOT_DIR,
                run_params=RUN_PARAMS,
                project_path=DUSTYCULT_PROJECT,
                julia=JULIA,
            )
            record_result(results, candidate_id, 'quick', quick_action, quick_row)
            print(f"  quick: {quick_row.get('status')} {quick_action} {quick_row.get('error') or ''}")

    out = pd.DataFrame(results)
    elapsed = time.monotonic() - started
    print(f'Finished {len(out)} candidate-mode rows in {elapsed:.1f} s')
    return out

### Smoke Test

Run one candidate first. If it completes or records a sensible warning/failure, run the full queue cell below.

In [7]:
MAX_CANDIDATES = 1
smoke_results = run_fit_queue(max_candidates=MAX_CANDIDATES)
display(smoke_results)

if not smoke_results.empty:
    smoke_id = str(smoke_results.iloc[0]['candidate_id'])
    with db_connect(DB_PATH) as conn:
        smoke_fits = load_dustycult_fits(conn, smoke_id)
    display(smoke_fits)
    artifact_dir = smoke_results.iloc[0].get('artifact_dir')
    if artifact_dir:
        artifact_path = Path(str(artifact_dir))
        print(f'Artifact dir exists: {artifact_path.exists()} -> {artifact_path}')

[1/1] stv_360777826205
  quick: failed run_missing DustyCult needs at least 12 valid g/V points; found 3.
Finished 1 candidate-mode rows in 0.1 s

       candidate_id   mode       action  status  runtime_sec         t0_jd      start_jd        end_jd  n_input_points  n_curve_points                                       artifact_dir                                              error
0  stv_360777826205  quick  run_missing  failed     0.031034  2.458414e+06  2.458413e+06  2.458415e+06               3               0  /Users/calder/code/malca/output/runs/dat3-full...  DustyCult needs at least 12 valid g/V points; ...

,candidate_id,mode,status,created_at,updated_at,runtime_sec,artifact_dir,input_path,config_path,manifest_path,command_json,config_json,controls_json,window_json,stellar_json,posterior_json,summary_json,stderr_tail,stdout_tail,error,t0_jd,start_jd,end_jd,n_input_points,n_curve_points
0,stv_360777826205,quick,failed,2026-07-12T22:37:29.056526+00:00,2026-07-12T22:37:29.056526+00:00,0.031034,/Users/calder/code/malca/output/runs/dat3-full...,None,None,None,[],{},"{""alpha_center"":0.0,""alpha_width"":2.0,""b_cente...","{""end_jd"":2458415.08134,""lc_path"":""/Users/cald...",None,None,"{""quality"":{""after_t0_points"":1,""band_counts"":...",,,DustyCult needs at least 12 valid g/V points; ...,2.458414e+06,2.458413e+06,2.458415e+06,3,0

Artifact dir exists: False -> /Users/calder/code/malca/output/runs/dat3-full-extended_2026-07-01-v4/review/dustycult/stv_360777826205/quick

### Full Remaining Quick Run

This sets `MAX_CANDIDATES = None`. Existing `ok` or `warning` quick fits are skipped, including the smoke-test result if it succeeded or warned.

In [8]:
MAX_CANDIDATES = None
full_results = run_fit_queue(max_candidates=MAX_CANDIDATES)
display(full_results)
display(full_results.groupby(['action', 'status'], dropna=False).size().reset_index(name='n'))

[1/71] stv_360777826205
  quick: failed retry_existing_failed DustyCult needs at least 12 valid g/V points; found 3.
[2/71] stv_197569226514
  quick: failed run_missing DustyCult t0 is outside the selected fit window. DustyCult needs at least 12 valid g/V points; found 7.
[3/71] stv_395138016907
  quick: warning run_missing DustyCult reported 18 divergent transitions.
[4/71] stv_163209415214
  quick: failed run_missing DustyCult t0 is outside the selected fit window.
[5/71] stv_403727411589
  quick: warning run_missing DustyCult reported 111 divergent transitions.
[6/71] stv_25770316308
  quick: warning run_missing DustyCult has only 12 valid g/V points. DustyCult input contains only one ASAS-SN band. DustyCult input spans only 11.99 days. DustyCult input has sparse coverage on one side of t0. DustyCult reported 8 divergent transitions.
[7/71] stv_584116028406
  quick: warning run_missing DustyCult input contains only one ASAS-SN band. DustyCult reported 3 divergent transitions.
[8/71] stv_154620038181
  quick: warning run_missing DustyCult input contains only one ASAS-SN band. DustyCult reported 19 divergent transitions.
[9/71] stv_180388640882
  quick: warning run_missing DustyCult input contains only one ASAS-SN band. DustyCult reported 2 divergent transitions.
[10/71] stv_17181027305
  quick: failed run_missing DustyCult needs at least 12 valid g/V points; found 3.
[11/71] stv_592705538522
  quick: failed run_missing DustyCult posterior credible intervals are degenerate. DustyCult input contains only one ASAS-SN band. DustyCult reported 81 divergent transitions.
[12/71] stv_601295761416
  quick: warning run_missing DustyCult input contains only one ASAS-SN band.
[13/71] stv_111669273145
  quick: failed run_missing DustyCult needs at least 12 valid g/V points; found 11.
[14/71] stv_395137575008
  quick: warning run_missing DustyCult reported 19 divergent transitions.
[15/71] stv_60130141761
  quick: warning run_missing DustyCult reported 4 divergent transitions.
[16/71] stv_68720714610
  quick: warning run_missing DustyCult input contains only one ASAS-SN band. DustyCult reported 13 divergent transitions.
[17/71] stv_541166985810
  quick: warning run_missing DustyCult input contains only one ASAS-SN band. DustyCult reported 14 divergent transitions.
[18/71] stv_300648087617
  quick: warning run_missing DustyCult has only 16 valid g/V points. DustyCult input contains only one ASAS-SN band. DustyCult input spans only 13.01 days. DustyCult reported 10 divergent transitions.
[19/71] stv_541166181486
  quick: warning run_missing DustyCult input contains only one ASAS-SN band. DustyCult reported 8 divergent transitions.
[20/71] stv_644245359876
  quick: warning run_missing DustyCult input contains only one ASAS-SN band.
[21/71] stv_446677131304
  quick: warning run_missing DustyCult has only 15 valid g/V points. DustyCult input contains only one ASAS-SN band.
[22/71] stv_566936751170
  quick: warning run_missing DustyCult has only 15 valid g/V points. DustyCult input contains only one ASAS-SN band. DustyCult input spans only 13.41 days. DustyCult reported 58 divergent transitions.
[23/71] stv_197569238413
  quick: failed run_missing DustyCult needs at least 12 valid g/V points; found 3.
[24/71] stv_566936725849
  quick: skipped existing warning
[25/71] stv_369367304600
  quick: skipped existing ok
[26/71] stv_266288257407
  quick: failed run_missing DustyCult t0 is outside the selected fit window. DustyCult needs at least 12 valid g/V points; found 9.
[27/71] stv_609885850038
  quick: warning run_missing DustyCult input contains only one ASAS-SN band. DustyCult reported 36 divergent transitions.
[28/71] stv_240518717560
  quick: warning run_missing DustyCult input contains only one ASAS-SN band. DustyCult reported 16 divergent transitions.
[29/71] stv_472446832201
  quick: warning run_missing DustyCult input contains only one ASAS-SN band. DustyCult reported 2 divergent transitions.
[30/71] stv_369368258528
  quick: warning run_missing DustyCult input contains only one ASAS-SN band. DustyCult reported 19 divergent transitions.
[31/71] stv_627065319105
  quick: warning run_missing DustyCult input contains only one ASAS-SN band.
[32/71] stv_489626538045
  quick: warning run_missing DustyCult input contains only one ASAS-SN band. DustyCult reported 24 divergent transitions.
[33/71] stv_94489594805
  quick: ok run_missing
[34/71] stv_446677119900
  quick: warning run_missing DustyCult has only 12 valid g/V points. DustyCult input contains only one ASAS-SN band. DustyCult reported 81 divergent transitions.
[35/71] stv_523987067704
  quick: warning run_missing DustyCult has only 22 valid g/V points. DustyCult input contains only one ASAS-SN band. DustyCult input has sparse coverage on one side of t0. DustyCult reported 16 divergent transitions.
[36/71] stv_42950519514
  quick: warning run_missing DustyCult input contains only one ASAS-SN band. DustyCult reported 15 divergent transitions.
[37/71] stv_601295730966
  quick: warning run_missing DustyCult input contains only one ASAS-SN band. DustyCult reported 3 divergent transitions.
[38/71] stv_283467842509
  quick: warning run_missing DustyCult input contains only one ASAS-SN band. DustyCult reported 14 divergent transitions.
[39/71] stv_532576256705
  quick: warning run_missing DustyCult input contains only one ASAS-SN band. DustyCult reported 106 divergent transitions.
[40/71] stv_249109213616
  quick: warning run_missing DustyCult input contains only one ASAS-SN band. DustyCult reported 16 divergent transitions.
[41/71] stv_283468165807
  quick: warning run_missing DustyCult reported 6 divergent transitions.
[42/71] stv_420907788679
  quick: warning run_missing DustyCult input contains only one ASAS-SN band. DustyCult reported 3 divergent transitions.
[43/71] stv_94489437356
  quick: warning run_missing DustyCult has only 16 valid g/V points. DustyCult input contains only one ASAS-SN band. DustyCult input has sparse coverage on one side of t0. DustyCult reported 8 divergent transitions.
[44/71] stv_489626566903
  quick: warning run_missing DustyCult input contains only one ASAS-SN band. DustyCult reported 7 divergent transitions.
[45/71] stv_128850429575
  quick: warning run_missing DustyCult input contains only one ASAS-SN band. DustyCult reported 34 divergent transitions.
[46/71] stv_240519504803
  quick: ok run_missing
[47/71] stv_68719676517
  quick: warning run_missing DustyCult input contains only one ASAS-SN band. DustyCult reported 116 divergent transitions.
[48/71] stv_163209590869
  quick: warning run_missing DustyCult input contains only one ASAS-SN band.
[49/71] stv_481036839646
  quick: warning run_missing DustyCult input contains only one ASAS-SN band. DustyCult reported 10 divergent transitions.
[50/71] stv_463857647562
  quick: warning run_missing DustyCult input contains only one ASAS-SN band. DustyCult reported 29 divergent transitions.
[51/71] stv_300648890329
  quick: warning run_missing DustyCult input contains only one ASAS-SN band. DustyCult input has sparse coverage on one side of t0. DustyCult reported 7 divergent transitions.
[52/71] stv_111669291649
  quick: warning run_missing DustyCult input contains only one ASAS-SN band. DustyCult reported 14 divergent transitions.
[53/71] stv_498216222923
  quick: failed run_missing DustyCult t0 is outside the selected fit window.
[54/71] stv_240518636016
  quick: warning run_missing DustyCult has only 16 valid g/V points. DustyCult input contains only one ASAS-SN band. DustyCult reported 8 divergent transitions.
[55/71] stv_446676921101
  quick: warning run_missing DustyCult has only 13 valid g/V points. DustyCult input contains only one ASAS-SN band. DustyCult reported 25 divergent transitions.
[56/71] stv_549755992463
  quick: warning run_missing DustyCult input contains only one ASAS-SN band. DustyCult reported 15 divergent transitions.
[57/71] stv_223338997633
  quick: warning run_missing DustyCult input contains only one ASAS-SN band.
[58/71] stv_8591303502
  quick: ok run_missing
[59/71] stv_523986354332
  quick: failed run_missing DustyCult t0 is outside the selected fit window.
[60/71] stv_25771086021
  quick: warning run_missing DustyCult input contains only one ASAS-SN band.
[61/71] stv_481036586933
  quick: failed run_missing DustyCult needs at least 12 valid g/V points; found 7.
[62/71] stv_532576054353
  quick: warning run_missing DustyCult input contains only one ASAS-SN band. DustyCult reported 8 divergent transitions.
[63/71] stv_592705518006
  quick: failed run_missing DustyCult needs at least 12 valid g/V points; found 5.
[64/71] stv_146029419304
  quick: failed run_missing DustyCult needs at least 12 valid g/V points; found 5.
[65/71] stv_369367489518
  quick: warning run_missing DustyCult input contains only one ASAS-SN band.
[66/71] stv_515396131751
  quick: warning run_missing DustyCult input contains only one ASAS-SN band. DustyCult reported 20 divergent transitions.
[67/71] stv_206158525635
  quick: warning run_missing DustyCult reported 2 divergent transitions.
[68/71] stv_111669557747
  quick: warning run_missing DustyCult has only 19 valid g/V points. DustyCult reported 19 divergent transitions.
[69/71] stv_644245286164
  quick: warning run_missing DustyCult has only 20 valid g/V points. DustyCult input contains only one ASAS-SN band. DustyCult input spans only 10.24 days. DustyCult reported 11 divergent transitions.
[70/71] stv_94489786439
  quick: failed run_missing DustyCult t0 is outside the selected fit window. DustyCult needs at least 12 valid g/V points; found 2.
[71/71] stv_180388903123
  quick: failed run_missing DustyCult t0 is outside the selected fit window.
Finished 71 candidate-mode rows in 181716.3 s

,candidate_id,mode,action,status,runtime_sec,t0_jd,start_jd,end_jd,n_input_points,n_curve_points,artifact_dir,error
0,stv_360777826205,quick,retry_existing_failed,failed,0.003039,2.458414e+06,2.458413e+06,2.458415e+06,3.0,0.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult needs at least 12 valid g/V points; ...
1,stv_197569226514,quick,run_missing,failed,0.018269,2.459224e+06,2.459297e+06,2.459346e+06,7.0,0.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult t0 is outside the selected fit windo...
2,stv_395138016907,quick,run_missing,warning,3406.404095,2.458201e+06,2.458081e+06,2.458321e+06,54.0,54.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult reported 18 divergent transitions.
3,stv_163209415214,quick,run_missing,failed,0.002573,2.460375e+06,2.460378e+06,2.460398e+06,14.0,0.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult t0 is outside the selected fit window.
4,stv_403727411589,quick,run_missing,warning,622.792783,2.458204e+06,2.458084e+06,2.458324e+06,89.0,89.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult reported 111 divergent transitions.
5,stv_25770316308,quick,run_missing,warning,399.436591,2.458785e+06,2.458778e+06,2.458792e+06,12.0,12.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult has only 12 valid g/V points. DustyC...
6,stv_584116028406,quick,run_missing,warning,4010.612331,2.460936e+06,2.460884e+06,2.460988e+06,80.0,80.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
7,stv_154620038181,quick,run_missing,warning,3193.433684,2.459812e+06,2.459738e+06,2.459885e+06,89.0,89.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
8,stv_180388640882,quick,run_missing,warning,6886.685287,2.460504e+06,2.460384e+06,2.460624e+06,152.0,152.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
9,stv_17181027305,quick,run_missing,failed,0.003559,2.460324e+06,2.460317e+06,2.460331e+06,3.0,0.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult needs at least 12 valid g/V points; ...
10,stv_592705538522,quick,run_missing,failed,75.978991,2.460918e+06,2.460798e+06,2.461038e+06,102.0,102.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult posterior credible intervals are deg...
11,stv_601295761416,quick,run_missing,warning,3721.315481,2.458558e+06,2.458462e+06,2.458654e+06,135.0,135.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band.
12,stv_111669273145,quick,run_missing,failed,0.028511,2.460276e+06,2.460269e+06,2.460280e+06,11.0,0.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult needs at least 12 valid g/V points; ...
13,stv_395137575008,quick,run_missing,warning,3837.270929,2.458394e+06,2.458307e+06,2.458481e+06,54.0,54.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult reported 19 divergent transitions.
14,stv_60130141761,quick,run_missing,warning,8115.414119,2.458455e+06,2.458335e+06,2.458575e+06,74.0,74.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult reported 4 divergent transitions.
15,stv_68720714610,quick,run_missing,warning,5281.216284,2.458433e+06,2.458313e+06,2.458553e+06,52.0,52.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
16,stv_541166985810,quick,run_missing,warning,11170.360484,2.460013e+06,2.459893e+06,2.460133e+06,196.0,196.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
17,stv_300648087617,quick,run_missing,warning,311.456541,2.458459e+06,2.458452e+06,2.458466e+06,16.0,16.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult has only 16 valid g/V points. DustyC...
18,stv_541166181486,quick,run_missing,warning,5324.495390,2.460511e+06,2.460391e+06,2.460631e+06,129.0,129.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
19,stv_644245359876,quick,run_missing,warning,2630.252613,2.458877e+06,2.458757e+06,2.458997e+06,107.0,107.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band.
20,stv_446677131304,quick,run_missing,warning,134.732191,2.458548e+06,2.458525e+06,2.458570e+06,15.0,15.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult has only 15 valid g/V points. DustyC...
21,stv_566936751170,quick,run_missing,warning,162.978253,2.460080e+06,2.460073e+06,2.460087e+06,15.0,15.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult has only 15 valid g/V points. DustyC...
22,stv_197569238413,quick,run_missing,failed,0.002813,2.458467e+06,2.458467e+06,2.458468e+06,3.0,0.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult needs at least 12 valid g/V points; ...
23,stv_566936725849,quick,skipped_existing_good,ok,NaN,2.460070e+06,2.460003e+06,2.460137e+06,NaN,NaN,,
24,stv_369367304600,quick,skipped_existing_good,ok,NaN,2.460763e+06,2.460643e+06,2.460883e+06,NaN,NaN,,
25,stv_266288257407,quick,run_missing,failed,0.003010,2.457809e+06,2.457848e+06,2.457891e+06,9.0,0.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult t0 is outside the selected fit windo...
26,stv_609885850038,quick,run_missing,warning,5204.199649,2.460743e+06,2.460623e+06,2.460863e+06,84.0,84.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
27,stv_240518717560,quick,run_missing,warning,4279.419186,2.458820e+06,2.458700e+06,2.458940e+06,72.0,72.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
28,stv_472446832201,quick,run_missing,warning,2192.685138,2.459837e+06,2.459717e+06,2.459957e+06,67.0,67.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
29,stv_369368258528,quick,run_missing,warning,5635.252601,2.460273e+06,2.460153e+06,2.460393e+06,78.0,78.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
30,stv_627065319105,quick,run_missing,warning,32871.500522,2.460753e+06,2.460633e+06,2.460873e+06,334.0,334.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band.
31,stv_489626538045,quick,run_missing,warning,3643.786076,2.460192e+06,2.460072e+06,2.460312e+06,80.0,80.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
32,stv_94489594805,quick,run_missing,ok,4285.641429,2.458386e+06,2.458266e+06,2.458506e+06,71.0,71.0,/Users/calder/code/malca/output/runs/dat3-full...,
33,stv_446677119900,quick,run_missing,warning,108.790284,2.459617e+06,2.459597e+06,2.459637e+06,12.0,12.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult has only 12 valid g/V points. DustyC...
34,stv_523987067704,quick,run_missing,warning,1192.985556,2.457546e+06,2.457426e+06,2.457666e+06,22.0,22.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult has only 22 valid g/V points. DustyC...
35,stv_42950519514,quick,run_missing,warning,2683.706956,2.459285e+06,2.459165e+06,2.459405e+06,50.0,50.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
36,stv_601295730966,quick,run_missing,warning,4932.160437,2.459771e+06,2.459651e+06,2.459891e+06,88.0,88.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
37,stv_283467842509,quick,run_missing,warning,361.905469,2.460846e+06,2.460826e+06,2.460867e+06,25.0,25.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
38,stv_532576256705,quick,run_missing,warning,1261.603230,2.458521e+06,2.458401e+06,2.458641e+06,137.0,137.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
39,stv_249109213616,quick,run_missing,warning,7236.908955,2.460344e+06,2.460224e+06,2.460464e+06,163.0,163.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
40,stv_283468165807,quick,run_missing,warning,606.278858,2.458230e+06,2.458110e+06,2.458350e+06,72.0,72.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult reported 6 divergent transitions.
41,stv_420907788679,quick,run_missing,warning,4439.604102,2.460614e+06,2.460504e+06,2.460724e+06,94.0,94.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
42,stv_94489437356,quick,run_missing,warning,1008.585230,2.460904e+06,2.460784e+06,2.461024e+06,16.0,16.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult has only 16 valid g/V points. DustyC...
43,stv_489626566903,quick,run_missing,warning,5871.703802,2.458863e+06,2.458743e+06,2.458983e+06,126.0,126.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
44,stv_128850429575,quick,run_missing,warning,932.439090,2.457504e+06,2.457384e+06,2.457624e+06,35.0,35.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
45,stv_240519504803,quick,run_missing,ok,2201.090668,2.458337e+06,2.458290e+06,2.458385e+06,31.0,31.0,/Users/calder/code/malca/output/runs/dat3-full...,
46,stv_68719676517,quick,run_missing,warning,313.066901,2.460787e+06,2.460667e+06,2.460907e+06,37.0,37.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
47,stv_163209590869,quick,run_missing,warning,1218.128649,2.459435e+06,2.459387e+06,2.459482e+06,60.0,60.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band.
48,stv_481036839646,quick,run_missing,warning,2750.316899,2.458097e+06,2.457977e+06,2.458217e+06,98.0,98.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
49,stv_463857647562,quick,run_missing,warning,3380.739823,2.460489e+06,2.460369e+06,2.460609e+06,116.0,116.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
50,stv_300648890329,quick,run_missing,warning,835.696278,2.457499e+06,2.457379e+06,2.457619e+06,26.0,26.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
51,stv_111669291649,quick,run_missing,warning,1531.123928,2.457349e+06,2.457252e+06,2.457447e+06,75.0,75.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
52,stv_498216222923,quick,run_missing,failed,0.003068,2.458983e+06,2.458900e+06,2.458926e+06,16.0,0.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult t0 is outside the selected fit window.
53,stv_240518636016,quick,run_missing,warning,336.589176,2.457656e+06,2.457600e+06,2.457713e+06,16.0,16.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult has only 16 valid g/V points. DustyC...
54,stv_446676921101,quick,run_missing,warning,557.041580,2.458900e+06,2.458819e+06,2.458980e+06,13.0,13.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult has only 13 valid g/V points. DustyC...
55,stv_549755992463,quick,run_missing,warning,1319.270049,2.460020e+06,2.459985e+06,2.460055e+06,33.0,33.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
56,stv_223338997633,quick,run_missing,warning,7181.868734,2.460548e+06,2.460428e+06,2.460668e+06,100.0,100.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band.
57,stv_8591303502,quick,run_missing,ok,6100.216269,2.458328e+06,2.458229e+06,2.458427e+06,85.0,85.0,/Users/calder/code/malca/output/runs/dat3-full...,
58,stv_523986354332,quick,run_missing,failed,0.002662,2.460773e+06,2.460220e+06,2.460589e+06,32.0,0.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult t0 is outside the selected fit window.
59,stv_25771086021,quick,run_missing,warning,1393.494092,2.458810e+06,2.458690e+06,2.458930e+06,48.0,48.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band.
60,stv_481036586933,quick,run_missing,failed,0.002697,2.458929e+06,2.458922e+06,2.458936e+06,7.0,0.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult needs at least 12 valid g/V points; ...
61,stv_532576054353,quick,run_missing,warning,751.008612,2.458770e+06,2.458747e+06,2.458793e+06,60.0,60.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
62,stv_592705518006,quick,run_missing,failed,0.002558,2.459752e+06,2.459745e+06,2.459759e+06,5.0,0.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult needs at least 12 valid g/V points; ...
63,stv_146029419304,quick,run_missing,failed,0.002144,2.458320e+06,2.458313e+06,2.458327e+06,5.0,0.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult needs at least 12 valid g/V points; ...
64,stv_369367489518,quick,run_missing,warning,1601.571065,2.459429e+06,2.459390e+06,2.459469e+06,37.0,37.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band.
65,stv_515396131751,quick,run_missing,warning,380.656671,2.459992e+06,2.459928e+06,2.460056e+06,36.0,36.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
66,stv_206158525635,quick,run_missing,warning,959.253070,2.458348e+06,2.458321e+06,2.458375e+06,71.0,71.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult reported 2 divergent transitions.
67,stv_111669557747,quick,run_missing,warning,253.809339,2.458325e+06,2.458297e+06,2.458353e+06,19.0,19.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult has only 19 valid g/V points. DustyC...
68,stv_644245286164,quick,run_missing,warning,615.442869,2.460130e+06,2.460123e+06,2.460137e+06,20.0,20.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult has only 20 valid g/V points. DustyC...
69,stv_94489786439,quick,run_missing,failed,0.002076,2.458516e+06,2.458507e+06,2.458508e+06,2.0,0.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult t0 is outside the selected fit windo...
70,stv_180388903123,quick,run_missing,failed,0.001950,2.458757e+06,2.458536e+06,2.458595e+06,12.0,0.0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult t0 is outside the selected fit window.

                  action   status   n
0  retry_existing_failed   failed   1
1            run_missing   failed  14
2            run_missing       ok   3
3            run_missing  warning  51
4  skipped_existing_good       ok   2

## Summary And Example Display

Use this after the smoke test or full run. It reloads from SQLite instead of trusting in-memory results.

In [9]:
candidate_ids = reviewed_dippers['candidate_id'].astype(str).tolist()
final_fits = reload_existing_fits(candidate_ids)

display(final_fits.groupby(['mode', 'status'], dropna=False).size().reset_index(name='n') if not final_fits.empty else Markdown('No DustyCult fits found.'))
display(final_fits.sort_values(['candidate_id', 'mode']) if not final_fits.empty else final_fits)

quick_final = final_fits[final_fits['mode'].astype(str).eq('quick')].copy() if not final_fits.empty else pd.DataFrame()
quick_good = quick_final[quick_final['status'].astype(str).isin(GOOD_STATUSES)].copy() if not quick_final.empty else pd.DataFrame()
print(f'Quick ok/warning fits: {len(quick_good)} / {len(reviewed_dippers)}')


def _display_rows_table(rows: list[tuple[str, str]] | list[tuple[str, str, str, str]]) -> None:
    if not rows:
        return
    frame = pd.DataFrame(rows)
    display(frame)


def _load_selected_dustycult_fit(candidate_id: str, mode: str | None = None):
    with db_connect(DB_PATH) as conn:
        fits = load_dustycult_fits(conn, candidate_id)
        fit_row = select_dustycult_display_row(fits, mode=mode)
        if fit_row is None:
            raise ValueError(f'No DustyCult fit row found for {candidate_id}')
        selected_mode = str(fit_row.get('mode') or 'quick')
        curves = load_dustycult_curve(conn, candidate_id, selected_mode)
    return fit_row, curves


def display_dustycult_review_panel(candidate_id: str, mode: str | None = None) -> None:
    fit_row, curves = _load_selected_dustycult_fit(candidate_id, mode)
    selected_mode = str(fit_row.get('mode') or 'quick')
    display(Markdown(f'### `{candidate_id}` DustyCult `{selected_mode}`'))
    _display_rows_table(dustycult_fit_metadata_rows(fit_row))
    if curves is not None and not curves.empty:
        display(build_dustycult_fit_figure(curves, fit_row, theme='white'))
    try:
        display(build_dustycult_occulter_figure(fit_row, theme='white', grid_n=501))
    except Exception as exc:
        display(Markdown(f'Occulter plot unavailable: `{exc}`'))
    _display_rows_table(dustycult_geometry_rows(fit_row))
    _display_rows_table(dustycult_posterior_rows(fit_row, limit=None))


if quick_good.empty:
    display(Markdown('No ok/warning quick fits are available yet.'))
else:
    example = quick_good.sort_values(['status', 'candidate_id']).iloc[0]
    display_dustycult_review_panel(str(example['candidate_id']), EXAMPLE_PLOT_MODE)

    mode   status   n
0  quick   failed  15
1  quick       ok   4
2  quick  warning  52

,candidate_id,mode,status,updated_at,runtime_sec,t0_jd,start_jd,end_jd,n_input_points,n_curve_points,artifact_dir,error
0,stv_111669273145,quick,failed,2026-07-13T04:49:26.444364+00:00,0.028511,2.460276e+06,2.460269e+06,2.460280e+06,11,0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult needs at least 12 valid g/V points; ...
1,stv_111669291649,quick,warning,2026-07-14T19:08:35.117218+00:00,1531.123928,2.457349e+06,2.457252e+06,2.457447e+06,75,75,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
2,stv_111669557747,quick,warning,2026-07-15T00:55:50.537948+00:00,253.809339,2.458325e+06,2.458297e+06,2.458353e+06,19,19,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult has only 19 valid g/V points. DustyC...
3,stv_128850429575,quick,warning,2026-07-14T15:44:44.952563+00:00,932.439090,2.457504e+06,2.457384e+06,2.457624e+06,35,35,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
4,stv_146029419304,quick,failed,2026-07-15T00:02:35.107381+00:00,0.002144,2.458320e+06,2.458313e+06,2.458327e+06,5,0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult needs at least 12 valid g/V points; ...
5,stv_154620038181,quick,warning,2026-07-13T01:51:22.140575+00:00,3193.433684,2.459812e+06,2.459738e+06,2.459885e+06,89,89,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
6,stv_163209415214,quick,failed,2026-07-12T23:34:15.731540+00:00,0.002573,2.460375e+06,2.460378e+06,2.460398e+06,14,0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult t0 is outside the selected fit window.
7,stv_163209590869,quick,warning,2026-07-14T16:46:57.243325+00:00,1218.128649,2.459435e+06,2.459387e+06,2.459482e+06,60,60,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band.
8,stv_17181027305,quick,failed,2026-07-13T03:46:08.973586+00:00,0.003559,2.460324e+06,2.460317e+06,2.460331e+06,3,0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult needs at least 12 valid g/V points; ...
9,stv_180388640882,quick,warning,2026-07-13T03:46:08.883158+00:00,6886.685287,2.460504e+06,2.460384e+06,2.460624e+06,152,152,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
10,stv_180388903123,quick,failed,2026-07-15T01:06:06.202158+00:00,0.001950,2.458757e+06,2.458536e+06,2.458595e+06,12,0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult t0 is outside the selected fit window.
11,stv_197569226514,quick,failed,2026-07-12T22:37:29.261548+00:00,0.018269,2.459224e+06,2.459297e+06,2.459346e+06,7,0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult t0 is outside the selected fit windo...
12,stv_197569238413,quick,failed,2026-07-13T15:05:34.991510+00:00,0.002813,2.458467e+06,2.458467e+06,2.458468e+06,3,0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult needs at least 12 valid g/V points; ...
13,stv_206158525635,quick,warning,2026-07-15T00:51:36.653142+00:00,959.253070,2.458348e+06,2.458321e+06,2.458375e+06,71,71,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult reported 2 divergent transitions.
14,stv_223338997633,quick,warning,2026-07-14T21:45:10.059939+00:00,7181.868734,2.460548e+06,2.460428e+06,2.460668e+06,100,100,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band.
15,stv_240518636016,quick,warning,2026-07-14T19:14:11.802850+00:00,336.589176,2.457656e+06,2.457600e+06,2.457713e+06,16,16,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult has only 16 valid g/V points. DustyC...
16,stv_240518717560,quick,warning,2026-07-13T17:43:38.803911+00:00,4279.419186,2.458820e+06,2.458700e+06,2.458940e+06,72,72,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
17,stv_240519504803,quick,ok,2026-07-14T16:21:26.043857+00:00,2201.090668,2.458337e+06,2.458290e+06,2.458385e+06,31,31,/Users/calder/code/malca/output/runs/dat3-full...,
18,stv_249109213616,quick,warning,2026-07-14T12:10:26.197339+00:00,7236.908955,2.460344e+06,2.460224e+06,2.460464e+06,163,163,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
19,stv_25770316308,quick,warning,2026-07-12T23:51:18.069256+00:00,399.436591,2.458785e+06,2.458778e+06,2.458792e+06,12,12,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult has only 12 valid g/V points. DustyC...
20,stv_25771086021,quick,warning,2026-07-14T23:50:03.898709+00:00,1393.494092,2.458810e+06,2.458690e+06,2.458930e+06,48,48,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band.
21,stv_266288257407,quick,failed,2026-07-13T15:05:35.110901+00:00,0.003010,2.457809e+06,2.457848e+06,2.457891e+06,9,0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult t0 is outside the selected fit windo...
22,stv_283467842509,quick,warning,2026-07-14T09:48:47.696229+00:00,361.905469,2.460846e+06,2.460826e+06,2.460867e+06,25,25,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
23,stv_283468165807,quick,warning,2026-07-14T12:20:32.491396+00:00,606.278858,2.458230e+06,2.458110e+06,2.458350e+06,72,72,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult reported 6 divergent transitions.
24,stv_300648087617,quick,warning,2026-07-13T12:48:02.346473+00:00,311.456541,2.458459e+06,2.458452e+06,2.458466e+06,16,16,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult has only 16 valid g/V points. DustyC...
25,stv_300648890329,quick,warning,2026-07-14T18:43:03.974520+00:00,835.696278,2.457499e+06,2.457379e+06,2.457619e+06,26,26,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
26,stv_360777826205,quick,failed,2026-07-12T22:37:29.184491+00:00,0.003039,2.458414e+06,2.458413e+06,2.458415e+06,3,0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult needs at least 12 valid g/V points; ...
27,stv_369367304600,quick,ok,2026-07-09T05:52:31.639486+00:00,16.276035,2.460712e+06,2.460704e+06,2.460725e+06,4,4,/Users/calder/code/malca/output/runs/dat3-full...,
28,stv_369367489518,quick,warning,2026-07-15T00:29:16.696038+00:00,1601.571065,2.459429e+06,2.459390e+06,2.459469e+06,37,37,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band.
29,stv_369368258528,quick,warning,2026-07-13T19:54:06.815362+00:00,5635.252601,2.460273e+06,2.460153e+06,2.460393e+06,78,78,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
30,stv_395137575008,quick,warning,2026-07-13T05:53:23.699197+00:00,3837.270929,2.458394e+06,2.458307e+06,2.458481e+06,54,54,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult reported 19 divergent transitions.
31,stv_395138016907,quick,warning,2026-07-12T23:34:15.649665+00:00,3406.404095,2.458201e+06,2.458081e+06,2.458321e+06,54,54,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult reported 18 divergent transitions.
32,stv_403727411589,quick,warning,2026-07-12T23:44:38.526649+00:00,622.792783,2.458204e+06,2.458084e+06,2.458324e+06,89,89,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult reported 111 divergent transitions.
33,stv_420907788679,quick,warning,2026-07-14T13:34:32.057015+00:00,4439.604102,2.460614e+06,2.460504e+06,2.460724e+06,94,94,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
34,stv_42950519514,quick,warning,2026-07-14T08:20:33.506265+00:00,2683.706956,2.459285e+06,2.459165e+06,2.459405e+06,50,50,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
35,stv_446676921101,quick,warning,2026-07-14T19:23:28.855221+00:00,557.041580,2.458900e+06,2.458819e+06,2.458980e+06,13,13,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult has only 13 valid g/V points. DustyC...
36,stv_446677119900,quick,warning,2026-07-14T07:15:56.743029+00:00,108.790284,2.459617e+06,2.459597e+06,2.459637e+06,12,12,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult has only 12 valid g/V points. DustyC...
37,stv_446677131304,quick,warning,2026-07-13T15:02:51.883785+00:00,134.732191,2.458548e+06,2.458525e+06,2.458570e+06,15,15,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult has only 15 valid g/V points. DustyC...
38,stv_463857647562,quick,warning,2026-07-14T18:29:08.227284+00:00,3380.739823,2.460489e+06,2.460369e+06,2.460609e+06,116,116,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
39,stv_472446832201,quick,warning,2026-07-13T18:20:11.504216+00:00,2192.685138,2.459837e+06,2.459717e+06,2.459957e+06,67,67,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
40,stv_481036586933,quick,failed,2026-07-14T23:50:03.960118+00:00,0.002697,2.458929e+06,2.458922e+06,2.458936e+06,7,0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult needs at least 12 valid g/V points; ...
41,stv_481036839646,quick,warning,2026-07-14T17:32:47.472568+00:00,2750.316899,2.458097e+06,2.457977e+06,2.458217e+06,98,98,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
42,stv_489626538045,quick,warning,2026-07-14T06:02:42.311449+00:00,3643.786076,2.460192e+06,2.460072e+06,2.460312e+06,80,80,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
43,stv_489626566903,quick,warning,2026-07-14T15:29:12.488377+00:00,5871.703802,2.458863e+06,2.458743e+06,2.458983e+06,126,126,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
44,stv_498216222923,quick,failed,2026-07-14T19:08:35.206858+00:00,0.003068,2.458983e+06,2.458900e+06,2.458926e+06,16,0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult t0 is outside the selected fit window.
45,stv_515396131751,quick,warning,2026-07-15T00:35:37.363279+00:00,380.656671,2.459992e+06,2.459928e+06,2.460056e+06,36,36,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
46,stv_523986354332,quick,failed,2026-07-14T23:26:50.420948+00:00,0.002662,2.460773e+06,2.460220e+06,2.460589e+06,32,0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult t0 is outside the selected fit window.
47,stv_523987067704,quick,warning,2026-07-14T07:35:49.746845+00:00,1192.985556,2.457546e+06,2.457426e+06,2.457666e+06,22,22,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult has only 22 valid g/V points. DustyC...
48,stv_532576054353,quick,warning,2026-07-15T00:02:34.978350+00:00,751.008612,2.458770e+06,2.458747e+06,2.458793e+06,60,60,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
49,stv_532576256705,quick,warning,2026-07-14T10:09:49.325892+00:00,1261.603230,2.458521e+06,2.458401e+06,2.458641e+06,137,137,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
50,stv_541166181486,quick,warning,2026-07-13T14:16:46.857375+00:00,5324.495390,2.460511e+06,2.460391e+06,2.460631e+06,129,129,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
51,stv_541166985810,quick,warning,2026-07-13T12:42:50.873871+00:00,11170.360484,2.460013e+06,2.459893e+06,2.460133e+06,196,196,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
52,stv_549755992463,quick,warning,2026-07-14T19:45:28.113003+00:00,1319.270049,2.460020e+06,2.459985e+06,2.460055e+06,33,33,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
53,stv_566936725849,quick,warning,2026-07-09T07:36:59.650249+00:00,2304.978950,2.460070e+06,2.460003e+06,2.460137e+06,76,76,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
54,stv_566936751170,quick,warning,2026-07-13T15:05:34.918053+00:00,162.978253,2.460080e+06,2.460073e+06,2.460087e+06,15,15,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult has only 15 valid g/V points. DustyC...
55,stv_584116028406,quick,warning,2026-07-13T00:58:08.671097+00:00,4010.612331,2.460936e+06,2.460884e+06,2.460988e+06,80,80,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
56,stv_592705518006,quick,failed,2026-07-15T00:02:35.056795+00:00,0.002558,2.459752e+06,2.459745e+06,2.459759e+06,5,0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult needs at least 12 valid g/V points; ...
57,stv_592705538522,quick,failed,2026-07-13T03:47:24.957347+00:00,75.978991,2.460918e+06,2.460798e+06,2.461038e+06,102,102,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult posterior credible intervals are deg...
58,stv_601295730966,quick,warning,2026-07-14T09:42:45.774665+00:00,4932.160437,2.459771e+06,2.459651e+06,2.459891e+06,88,88,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
59,stv_601295761416,quick,warning,2026-07-13T04:49:26.314072+00:00,3721.315481,2.458558e+06,2.458462e+06,2.458654e+06,135,135,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band.
60,stv_60130141761,quick,warning,2026-07-13T08:08:39.129367+00:00,8115.414119,2.458455e+06,2.458335e+06,2.458575e+06,74,74,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult reported 4 divergent transitions.
61,stv_609885850038,quick,warning,2026-07-13T16:32:19.362933+00:00,5204.199649,2.460743e+06,2.460623e+06,2.460863e+06,84,84,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
62,stv_627065319105,quick,warning,2026-07-14T05:01:58.504676+00:00,32871.500522,2.460753e+06,2.460633e+06,2.460873e+06,334,334,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band.
63,stv_644245286164,quick,warning,2026-07-15T01:06:06.106669+00:00,615.442869,2.460130e+06,2.460123e+06,2.460137e+06,20,20,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult has only 20 valid g/V points. DustyC...
64,stv_644245359876,quick,warning,2026-07-13T15:00:37.138845+00:00,2630.252613,2.458877e+06,2.458757e+06,2.458997e+06,107,107,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band.
65,stv_68719676517,quick,warning,2026-07-14T16:26:39.123059+00:00,313.066901,2.460787e+06,2.460667e+06,2.460907e+06,37,37,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
66,stv_68720714610,quick,warning,2026-07-13T09:36:40.475806+00:00,5281.216284,2.458433e+06,2.458313e+06,2.458553e+06,52,52,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult input contains only one ASAS-SN band...
67,stv_8591303502,quick,ok,2026-07-14T23:26:50.346558+00:00,6100.216269,2.458328e+06,2.458229e+06,2.458427e+06,85,85,/Users/calder/code/malca/output/runs/dat3-full...,
68,stv_94489437356,quick,warning,2026-07-14T13:51:20.643835+00:00,1008.585230,2.460904e+06,2.460784e+06,2.461024e+06,16,16,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult has only 16 valid g/V points. DustyC...
69,stv_94489594805,quick,ok,2026-07-14T07:14:07.941320+00:00,4285.641429,2.458386e+06,2.458266e+06,2.458506e+06,71,71,/Users/calder/code/malca/output/runs/dat3-full...,
70,stv_94489786439,quick,failed,2026-07-15T01:06:06.151748+00:00,0.002076,2.458516e+06,2.458507e+06,2.458508e+06,2,0,/Users/calder/code/malca/output/runs/dat3-full...,DustyCult t0 is outside the selected fit windo...

Quick ok/warning fits: 56 / 71

### `stv_240519504803` DustyCult `quick`

            0                                                  1
0        mode                                              quick
1      status                                                 ok
2     runtime                                         2201.091 s
3      window                                 2.5e+06 to 2.5e+06
4       bands                                         V:15, g:16
5  input span                                            87.01 d
6    baseline                                          gp_masked
7    artifact  /Users/calder/code/malca/output/runs/dat3-full...

                0           1
0              t0  2.4583e+06
1               v     0.55279
2               b     0.03883
3      b / R_star     0.00647
4            tau0     0.45805
5    lambda0 [nm]   656.89032
6           alpha    13.76961
7         sigma_y     0.94619
8    sigma_x_plus    11.29524
9   sigma_x_minus    11.62543
10         R_star     5.99919
11             u1           0
12             u2           0

               0          1          2          3
0          alpha    13.7696     12.536    14.7664
1              b     0.0388    -0.5743     0.5537
2        lambda0   656.8903   599.0587   723.2834
3  sigma_x_minus    11.6254     9.4853    14.3704
4   sigma_x_plus    11.2952      9.391    14.3577
5        sigma_y     0.9462     0.9153     0.9875
6             t0  2.458e+06  2.458e+06  2.458e+06
7           tau0     0.4581     0.1098     1.6489
8              v     0.5528     0.4694     0.6864