# Corroborated same-band mask propagation for all reviewed dippers

Sidecar diagnostic only: compare the current production masked per-camera GP with the same pipeline after propagating connected event intervals corroborated by at least two cameras. Production source is not modified.

In [1]:
from contextlib import contextmanager
import json
from pathlib import Path
import sqlite3
import sys

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from IPython.display import display
from matplotlib.backends.backend_pdf import PdfPages

candidate_roots = [Path.cwd().resolve(), *Path.cwd().resolve().parents]
repo_root = next((p for p in candidate_roots if (p / 'pyproject.toml').is_file() and (p / 'malca' / 'core' / 'baseline.py').is_file()), None)
if repo_root is None:
    raise RuntimeError(f'Could not find the MALCA repository above {Path.cwd()}')
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))

import malca.core.baseline as baseline_module
from malca.config import (
    GP_BRIGHT_SIGMA_THRESH, GP_DIP_SIGMA_THRESH, GP_MIN_GP_POINTS, GP_PAD_DAYS,
    GP_STIFF_MIN_DAYS, GP_STIFF_SCALE_FRACTION,
)
from malca.core.utils import clean_lc
from malca.io.lightcurve_io import load_lightcurve_df, to_asassn_algorithm_frame
from malca.plotting.lightcurve_publication import FIG_SINGLE_COL_WIDTH, PUBLICATION_STYLE, finalize_publication_figure
from malca.review.native_lightcurve import resolve_lightcurve_path
from malca.review.store import get_candidate_payload
from malca.stv.events import DEFAULT_BASELINE_KWARGS, score_events_bayesian

JD_OFFSET = 2458000.0
RUN_ROOT = repo_root / 'output' / 'runs' / 'dat3-full-extended_2026-07-01-v4'
RUN_PARAMS = json.loads((RUN_ROOT / 'run_params.json').read_text())
REVIEW_DB = RUN_ROOT / 'review' / 'review.db'
OUTPUT_DIR = repo_root / 'output' / 'pdf' / 'baseline_methods' / 'diagnostics' / 'reviewed_dippers'
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
PDF_PATH = OUTPUT_DIR / 'corroborated_mask_propagation_reviewed_dippers.pdf'
MANIFEST_PATH = OUTPUT_DIR / 'corroborated_mask_propagation_reviewed_dippers.csv'
CAMERA_PALETTE = ('#0072B2', '#009E73', '#56B4E9', '#6A3D9A', '#7F7F7F', '#E69F00', '#332288', '#44AA99', '#999933', '#8C6D31', '#333333', '#117733')

COHORT_SQL = '''
SELECT c.candidate_id, c.asas_sn_id
FROM candidates AS c
INNER JOIN reviews AS r ON r.candidate_id = c.candidate_id
WHERE lower(trim(coalesce(r.event_class, ''))) = ?
ORDER BY c.candidate_id
'''

/opt/homebrew/Caskroom/miniconda/base/envs/malca/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
def load_reviewed_dippers():
    read_only_uri = f'file:{REVIEW_DB.as_posix()}?mode=ro'
    with sqlite3.connect(read_only_uri, uri=True) as connection:
        cohort = pd.read_sql_query(COHORT_SQL, connection, params=('dipper',))
        paths = []
        for candidate_id in cohort['candidate_id'].astype(str):
            payload = get_candidate_payload(connection, candidate_id)
            resolved = resolve_lightcurve_path(payload, RUN_ROOT)
            paths.append(str(resolved.resolve()) if resolved is not None else None)
    cohort['resolved_lightcurve_path'] = paths
    if cohort['candidate_id'].duplicated().any():
        raise AssertionError('Reviewed-dipper query returned duplicate candidate IDs.')
    return cohort

def select_best_band(cleaned):
    bands = pd.to_numeric(cleaned['v_g_band'], errors='coerce')
    counts = bands.value_counts()
    candidates = [band for band in (0.0, 1.0) if counts.get(band, 0) > 0]
    if not candidates:
        raise ValueError('No recognized g or V band observations.')
    band_value = max(candidates, key=lambda band: (int(counts.get(band, 0)), band == 0.0))
    return band_value, {0.0: 'g', 1.0: 'V'}[band_value]

def prepare_lightcurve(candidate_row):
    path_value = candidate_row['resolved_lightcurve_path']
    if not path_value or not Path(path_value).is_file():
        raise FileNotFoundError(path_value)
    canonical = load_lightcurve_df(Path(path_value), apply_quality=True)
    cleaned = clean_lc(to_asassn_algorithm_frame(canonical)).reset_index(drop=True)
    band_value, band_label = select_best_band(cleaned)
    bands = pd.to_numeric(cleaned['v_g_band'], errors='coerce')
    lightcurve = cleaned.loc[np.isclose(bands, band_value)].copy().reset_index(drop=True)
    return lightcurve, band_label

cohort = load_reviewed_dippers()
if len(cohort) != 183:
    raise AssertionError(f'Expected 183 reviewed dippers, found {len(cohort)}.')
print(f'Reviewed dippers: {len(cohort)}')

Reviewed dippers: 183

In [3]:
def initial_intervals_by_camera(lightcurve):
    intervals_by_camera = {}
    for camera, sub in lightcurve.groupby('camera#', sort=True):
        ordered = sub.sort_values('JD')
        t = ordered['JD'].to_numpy(float)
        mag = ordered['mag'].to_numpy(float)
        error = ordered['error'].to_numpy(float)
        finite = np.isfinite(t) & np.isfinite(mag)
        median_mag = float(np.nanmedian(mag[finite]))
        base_rough = baseline_module._compute_base_rough(
            t, mag, error, finite, median_mag, auto_scale_gp=True,
            min_gp_points=GP_MIN_GP_POINTS, stiff_scale_fraction=GP_STIFF_SCALE_FRACTION,
            stiff_min_days=GP_STIFF_MIN_DAYS, S0=DEFAULT_BASELINE_KWARGS['S0'], q=DEFAULT_BASELINE_KWARGS['q'],
        )
        flags, _, _, _ = baseline_module._mask_excursions(
            t, mag, base_rough, finite, median_mag, mag_err=error,
            dip_sigma_thresh=GP_DIP_SIGMA_THRESH, bright_sigma_thresh=GP_BRIGHT_SIGMA_THRESH, pad_days=GP_PAD_DAYS,
        )
        flagged_indices = np.flatnonzero(flags)
        runs = np.split(flagged_indices, np.flatnonzero(np.diff(flagged_indices) > 1) + 1) if flagged_indices.size else []
        intervals_by_camera[camera] = [(float(t[run[0]]) - GP_PAD_DAYS, float(t[run[-1]]) + GP_PAD_DAYS) for run in runs if run.size]
    return intervals_by_camera

def corroborated_intervals(intervals_by_camera, min_cameras=2):
    tagged = sorted((float(lo), float(hi), camera) for camera, intervals in intervals_by_camera.items() for lo, hi in intervals)
    if not tagged:
        return []
    components = []
    current_lo, current_hi, current_camera = tagged[0]
    current_cameras = {current_camera}
    for lo, hi, camera in tagged[1:]:
        if lo <= current_hi:
            current_hi = max(current_hi, hi)
            current_cameras.add(camera)
        else:
            if len(current_cameras) >= int(min_cameras):
                components.append((current_lo, current_hi))
            current_lo, current_hi, current_cameras = lo, hi, {camera}
    if len(current_cameras) >= int(min_cameras):
        components.append((current_lo, current_hi))
    return components

original_mask_excursions = baseline_module._mask_excursions

@contextmanager
def propagate_intervals(extra_intervals):
    def mask_with_propagation(*args, **kwargs):
        flags, keep, intervals, s0 = original_mask_excursions(*args, **kwargs)
        t = np.asarray(args[0], float)
        added = np.zeros(len(t), dtype=bool)
        for lo, hi in extra_intervals:
            added |= (t >= float(lo)) & (t <= float(hi))
        flags = np.asarray(flags, bool) | added
        keep = np.asarray(keep, bool) & ~added
        intervals = baseline_module._union_intervals(list(intervals) + list(extra_intervals))
        return flags, keep, intervals, s0
    baseline_module._mask_excursions = mask_with_propagation
    try:
        yield
    finally:
        baseline_module._mask_excursions = original_mask_excursions

def run_comparison(lightcurve):
    current = baseline_module.per_camera_gp_baseline_masked(lightcurve, **DEFAULT_BASELINE_KWARGS).reset_index(drop=True)
    camera_intervals = initial_intervals_by_camera(lightcurve)
    shared_intervals = corroborated_intervals(camera_intervals, min_cameras=2)
    with propagate_intervals(shared_intervals):
        propagated = baseline_module.per_camera_gp_baseline_masked(lightcurve, **DEFAULT_BASELINE_KWARGS).reset_index(drop=True)
    return current, propagated, shared_intervals

EVENT_SCORING_KWARGS = {
    'p_points': int(RUN_PARAMS['p_points']),
    'mag_points': int(RUN_PARAMS['mag_points']),
    'trigger_mode': str(RUN_PARAMS['trigger_mode']),
    'significance_threshold': float(RUN_PARAMS['significance_threshold']),
    'run_min_points': int(RUN_PARAMS['run_min_points']),
    'max_gap_points': int(RUN_PARAMS['run_max_gap_points']),
    'run_max_gap_days': RUN_PARAMS['run_max_gap_days'],
    'run_min_duration_days': RUN_PARAMS['run_min_duration_days'],
    'compute_event_prob': True,
}

def production_event_run_mask(lightcurve, baseline_result):
    event_mask = np.zeros(len(lightcurve), dtype=bool)
    counts = {}
    for kind in ('dip', 'jump'):
        score = score_events_bayesian(
            lightcurve, kind=kind, baseline_func=None, df_base=baseline_result,
            logbf_threshold=float(RUN_PARAMS[f'logbf_threshold_{kind}']),
            **EVENT_SCORING_KWARGS,
        )
        indices = np.asarray(score['event_indices'], dtype=int)
        if indices.size:
            event_mask[indices] = True
        counts[kind] = int(indices.size)
    counts['either'] = int(event_mask.sum())
    return event_mask, counts

In [4]:
def camera_colors(lightcurve):
    cameras = sorted(lightcurve['camera#'].dropna().unique(), key=str)
    return {camera: CAMERA_PALETTE[i % len(CAMERA_PALETTE)] for i, camera in enumerate(cameras)}

def plot_baseline_panel(ax, frame, colors, title):
    for camera, sub in frame.groupby('camera#', sort=True):
        sub = sub.sort_values('JD')
        x = sub['JD'].to_numpy(float) - JD_OFFSET
        color = colors[camera]
        ax.scatter(x, sub['mag'], s=5, color=color, edgecolors='black', linewidths=0.18, zorder=2)
        ax.plot(x, sub['baseline'], color=color, linewidth=1.1, zorder=3)
        event_run = sub['event_run'].fillna(False).to_numpy(bool)
        if event_run.any():
            ax.scatter(x[event_run], sub.loc[event_run, 'mag'], s=13, marker='x', color='#b2182b', linewidths=0.7, zorder=5)
    ax.invert_yaxis()
    ax.set_ylabel(r'$m_i$ [mag]')
    ax.set_title(title, fontsize=8, pad=3)

def plot_residual_panel(ax, frame, colors, title):
    for camera, sub in frame.groupby('camera#', sort=True):
        sub = sub.sort_values('JD')
        x = sub['JD'].to_numpy(float) - JD_OFFSET
        color = colors[camera]
        ax.scatter(x, sub['resid'], s=5, color=color, edgecolors='black', linewidths=0.18, zorder=2)
        event_run = sub['event_run'].fillna(False).to_numpy(bool)
        if event_run.any():
            ax.scatter(x[event_run], sub.loc[event_run, 'resid'], s=13, marker='x', color='#b2182b', linewidths=0.7, zorder=5)
    ax.axhline(0, color='0.25', linewidth=0.7)
    ax.invert_yaxis()
    ax.set_ylabel(r'$r_i$ [mag]')
    ax.set_title(title, fontsize=8, pad=3)

def make_page(candidate_row, band_label, lightcurve, current, propagated, current_event_mask, propagated_event_mask):
    colors = camera_colors(lightcurve)
    current = current.copy()
    propagated = propagated.copy()
    current['event_run'] = np.asarray(current_event_mask, dtype=bool)
    propagated['event_run'] = np.asarray(propagated_event_mask, dtype=bool)
    with plt.rc_context(PUBLICATION_STYLE):
        fig, axes = plt.subplots(4, 1, figsize=(FIG_SINGLE_COL_WIDTH, 8.0), sharex=True)
        plot_baseline_panel(axes[0], current, colors, 'Current masked per-camera GP')
        plot_baseline_panel(axes[1], propagated, colors, 'Corroborated-mask per-camera GP')
        plot_residual_panel(axes[2], current, colors, 'Current residual')
        plot_residual_panel(axes[3], propagated, colors, 'Propagated-mask residual')
        axes[1].set_ylim(axes[0].get_ylim())
        residual_values = np.concatenate([current['resid'].to_numpy(float), propagated['resid'].to_numpy(float)])
        residual_values = residual_values[np.isfinite(residual_values)]
        residual_limit = max(0.15, float(np.max(np.abs(residual_values))) * 1.05)
        axes[2].set_ylim(residual_limit, -residual_limit)
        axes[3].set_ylim(residual_limit, -residual_limit)
        axes[-1].set_xlabel('JD - 2458000')
        for ax in axes:
            ax.tick_params(direction='in', top=True, right=True)
        source_id = candidate_row.get('asas_sn_id')
        if pd.isna(source_id) or not str(source_id).strip():
            source_id = candidate_row['candidate_id']
        fig.suptitle(f'ASAS-SN {str(source_id).strip()}, {band_label} band', fontsize=8)
        finalize_publication_figure(fig, rect=(0, 0, 1, 0.982))
        return fig

In [5]:
manifest_rows = []
with PdfPages(PDF_PATH) as atlas_pdf:
    for position, (_, candidate_row) in enumerate(cohort.iterrows(), start=1):
        candidate_id = str(candidate_row['candidate_id'])
        print(f'[{position:03d}/{len(cohort):03d}] {candidate_id}', end=' ... ')
        try:
            lightcurve, band_label = prepare_lightcurve(candidate_row)
            current, propagated, shared_intervals = run_comparison(lightcurve)
            current_event_mask, current_event_counts = production_event_run_mask(lightcurve, current)
            propagated_event_mask, propagated_event_counts = production_event_run_mask(lightcurve, propagated)
            figure = make_page(
                candidate_row, band_label, lightcurve, current, propagated,
                current_event_mask, propagated_event_mask,
            )
            atlas_pdf.savefig(figure)
            plt.close(figure)
            initial_masked = int(current['is_masked'].fillna(False).sum())
            propagated_masked = int(propagated['is_masked'].fillna(False).sum())
            manifest_rows.append({
                'event_class': 'dipper', 'candidate_id': candidate_id, 'asas_sn_id': candidate_row.get('asas_sn_id'),
                'lightcurve_path': candidate_row.get('resolved_lightcurve_path'), 'band': band_label,
                'n_points': int(len(lightcurve)), 'n_cameras': int(lightcurve['camera#'].nunique()),
                'initial_masked': initial_masked, 'propagated_masked': propagated_masked,
                'added_masked': propagated_masked - initial_masked,
                'initial_event_run_points': current_event_counts['either'],
                'initial_dip_run_points': current_event_counts['dip'],
                'initial_jump_run_points': current_event_counts['jump'],
                'propagated_event_run_points': propagated_event_counts['either'],
                'propagated_dip_run_points': propagated_event_counts['dip'],
                'propagated_jump_run_points': propagated_event_counts['jump'],
                'initial_mask_fraction': initial_masked / len(lightcurve),
                'propagated_mask_fraction': propagated_masked / len(lightcurve),
                'corroborated_intervals': int(len(shared_intervals)),
                'corroborated_duration_days': float(sum(hi - lo for lo, hi in shared_intervals)),
                'initial_consensus_cameras': int(current.groupby('camera#')['needs_consensus'].any().sum()),
                'propagated_consensus_cameras': int(propagated.groupby('camera#')['needs_consensus'].any().sum()),
                'initial_sources': ','.join(sorted(current['baseline_source'].dropna().astype(str).unique())),
                'propagated_sources': ','.join(sorted(propagated['baseline_source'].dropna().astype(str).unique())),
                'status': 'ok', 'error': '',
            })
            print(
                f'{len(lightcurve)} points, {lightcurve["camera#"].nunique()} cameras, '
                f'{current_event_counts["either"]} -> {propagated_event_counts["either"]} event-run points'
            )
        except Exception as exc:
            manifest_rows.append({
                'event_class': 'dipper', 'candidate_id': candidate_id, 'asas_sn_id': candidate_row.get('asas_sn_id'),
                'lightcurve_path': candidate_row.get('resolved_lightcurve_path'), 'band': '',
                'n_points': 0, 'n_cameras': 0, 'initial_masked': 0, 'propagated_masked': 0, 'added_masked': 0,
                'initial_event_run_points': 0, 'initial_dip_run_points': 0, 'initial_jump_run_points': 0,
                'propagated_event_run_points': 0, 'propagated_dip_run_points': 0, 'propagated_jump_run_points': 0,
                'initial_mask_fraction': np.nan, 'propagated_mask_fraction': np.nan,
                'corroborated_intervals': 0, 'corroborated_duration_days': 0.0,
                'initial_consensus_cameras': 0, 'propagated_consensus_cameras': 0,
                'initial_sources': '', 'propagated_sources': '',
                'status': 'failed', 'error': f'{type(exc).__name__}: {exc}',
            })
            print(f'FAILED: {type(exc).__name__}: {exc}')

manifest = pd.DataFrame(manifest_rows)
manifest.to_csv(MANIFEST_PATH, index=False)
display(manifest['status'].value_counts().rename_axis('status').to_frame('candidates'))
display(manifest.groupby('band').size().rename('candidates').to_frame())
display(manifest['added_masked'].describe().to_frame())
print(PDF_PATH)
print(MANIFEST_PATH)
failures = manifest.loc[manifest['status'] != 'ok']
if not failures.empty:
    display(failures)
    raise RuntimeError(f'{len(failures)} reviewed-dipper candidates failed.')
if len(manifest) != 183:
    raise AssertionError(f'Expected 183 manifest rows, got {len(manifest)}.')

[001/183] stv_103079502524 ...

OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.

740 points, 2 cameras, 2 -> 2 event-run points
[002/183] stv_103080542701 ...

687 points, 2 cameras, 0 -> 0 event-run points
[003/183] stv_111669273145 ...

1514 points, 4 cameras, 6 -> 6 event-run points
[004/183] stv_111669291649 ...

1404 points, 4 cameras, 45 -> 45 event-run points
[005/183] stv_111669305159 ...

592 points, 2 cameras, 46 -> 75 event-run points
[006/183] stv_111669455609 ...

714 points, 2 cameras, 122 -> 137 event-run points
[007/183] stv_111669512802 ...

698 points, 5 cameras, 5 -> 5 event-run points
[008/183] stv_111669557747 ...

683 points, 2 cameras, 57 -> 57 event-run points
[009/183] stv_111670309173 ...

614 points, 4 cameras, 4 -> 4 event-run points
[010/183] stv_111670444883 ...

639 points, 4 cameras, 4 -> 2 event-run points
[011/183] stv_111670547411 ...

676 points, 2 cameras, 17 -> 17 event-run points
[012/183] stv_120259148405 ...

670 points, 2 cameras, 74 -> 82 event-run points
[013/183] stv_120259356690 ...

1114 points, 4 cameras, 220 -> 240 event-run points
[014/183] stv_120259384073 ...

645 points, 2 cameras, 27 -> 27 event-run points
[015/183] stv_120259975222 ...

701 points, 2 cameras, 0 -> 0 event-run points
[016/183] stv_128850429575 ...

794 points, 4 cameras, 56 -> 56 event-run points
[017/183] stv_137440061640 ...

986 points, 5 cameras, 53 -> 53 event-run points
[018/183] stv_146029052740 ...

632 points, 2 cameras, 103 -> 110 event-run points
[019/183] stv_146029419304 ...

954 points, 5 cameras, 0 -> 0 event-run points
[020/183] stv_146029595645 ...

558 points, 2 cameras, 0 -> 0 event-run points
[021/183] stv_154618944199 ...

938 points, 5 cameras, 45 -> 47 event-run points
[022/183] stv_154620038181 ...

987 points, 5 cameras, 36 -> 38 event-run points
[023/183] stv_163209415214 ...

1382 points, 8 cameras, 14 -> 27 event-run points
[024/183] stv_163209590869 ...

1066 points, 5 cameras, 23 -> 33 event-run points
[025/183] stv_171799189280 ...

1070 points, 5 cameras, 3 -> 3 event-run points
[026/183] stv_17180004254 ...

1196 points, 4 cameras, 103 -> 105 event-run points
[027/183] stv_17180374105 ...

983 points, 4 cameras, 17 -> 17 event-run points
[028/183] stv_17180437911 ...

1056 points, 3 cameras, 0 -> 0 event-run points
[029/183] stv_17181027305 ...

1409 points, 4 cameras, 0 -> 0 event-run points
[030/183] stv_180388640882 ...

1491 points, 7 cameras, 139 -> 140 event-run points
[031/183] stv_180388903123 ...

1099 points, 5 cameras, 6 -> 10 event-run points
[032/183] stv_188978596613 ...

1758 points, 11 cameras, 87 -> 87 event-run points
[033/183] stv_188979090903 ...

457 points, 5 cameras, 15 -> 15 event-run points
[034/183] stv_188979142258 ...

1694 points, 8 cameras, 11 -> 21 event-run points
[035/183] stv_197569146752 ...

1256 points, 5 cameras, 123 -> 263 event-run points
[036/183] stv_197569226514 ...

1011 points, 6 cameras, 2 -> 2 event-run points
[037/183] stv_197569238413 ...

1130 points, 5 cameras, 4 -> 4 event-run points
[038/183] stv_206158504352 ...

931 points, 5 cameras, 97 -> 98 event-run points
[039/183] stv_206158525635 ...

2018 points, 11 cameras, 114 -> 121 event-run points
[040/183] stv_214748665650 ...

643 points, 6 cameras, 14 -> 17 event-run points
[041/183] stv_214748985701 ...

1872 points, 11 cameras, 5 -> 5 event-run points
[042/183] stv_223338997633 ...

1052 points, 6 cameras, 30 -> 32 event-run points
[043/183] stv_240518568351 ...

589 points, 8 cameras, 0 -> 0 event-run points
[044/183] stv_240518636016 ...

1006 points, 5 cameras, 140 -> 138 event-run points
[045/183] stv_240518717560 ...

575 points, 5 cameras, 31 -> 40 event-run points
[046/183] stv_240519504803 ...

989 points, 5 cameras, 43 -> 53 event-run points
[047/183] stv_249109213616 ...

1224 points, 5 cameras, 206 -> 380 event-run points
[048/183] stv_25770235550 ...

1350 points, 5 cameras, 327 -> 328 event-run points
[049/183] stv_25770316308 ...

1310 points, 4 cameras, 0 -> 0 event-run points
[050/183] stv_25770384706 ...

1112 points, 3 cameras, 0 -> 0 event-run points
[051/183] stv_25771086021 ...

588 points, 2 cameras, 0 -> 0 event-run points
[052/183] stv_266288191401 ...

1272 points, 5 cameras, 8 -> 8 event-run points
[053/183] stv_266288257407 ...

1350 points, 7 cameras, 36 -> 36 event-run points
[054/183] stv_266288875581 ...

1887 points, 11 cameras, 149 -> 182 event-run points
[055/183] stv_266289132701 ...

1445 points, 4 cameras, 0 -> 2 event-run points
[056/183] stv_283467842509 ...

1153 points, 5 cameras, 62 -> 136 event-run points
[057/183] stv_283467971446 ...

946 points, 7 cameras, 0 -> 0 event-run points
[058/183] stv_283468165807 ...

1085 points, 3 cameras, 209 -> 209 event-run points
[059/183] stv_283468931829 ...

1073 points, 3 cameras, 21 -> 24 event-run points
[060/183] stv_292057989013 ...

1388 points, 6 cameras, 123 -> 126 event-run points
[061/183] stv_292059016008 ...

930 points, 5 cameras, 0 -> 0 event-run points
[062/183] stv_300648040390 ...

1115 points, 3 cameras, 277 -> 288 event-run points
[063/183] stv_300648087617 ...

1634 points, 6 cameras, 5 -> 51 event-run points
[064/183] stv_300648890329 ...

1022 points, 5 cameras, 2 -> 4 event-run points
[065/183] stv_309238625577 ...

1300 points, 5 cameras, 0 -> 0 event-run points
[066/183] stv_317828555902 ...

1754 points, 3 cameras, 131 -> 131 event-run points
[067/183] stv_317828613008 ...

1928 points, 7 cameras, 0 -> 0 event-run points
[068/183] stv_326417748428 ...

2284 points, 11 cameras, 41 -> 43 event-run points
[069/183] stv_326417838270 ...

1125 points, 5 cameras, 17 -> 9 event-run points
[070/183] stv_343598086600 ...

1459 points, 5 cameras, 164 -> 163 event-run points
[071/183] stv_34360122433 ...

1183 points, 4 cameras, 12 -> 15 event-run points
[072/183] stv_34360173609 ...

1150 points, 3 cameras, 82 -> 83 event-run points
[073/183] stv_352187778169 ...

934 points, 5 cameras, 34 -> 32 event-run points
[074/183] stv_352188453021 ...

1140 points, 3 cameras, 89 -> 89 event-run points
[075/183] stv_360777789109 ...

1121 points, 5 cameras, 4 -> 4 event-run points
[076/183] stv_360777826205 ...

1643 points, 5 cameras, 0 -> 0 event-run points
[077/183] stv_360778187147 ...

1365 points, 8 cameras, 0 -> 0 event-run points
[078/183] stv_369367234804 ...

1702 points, 7 cameras, 61 -> 61 event-run points
[079/183] stv_369367304600 ...

782 points, 5 cameras, 68 -> 77 event-run points
[080/183] stv_369367489518 ...

909 points, 5 cameras, 92 -> 84 event-run points
[081/183] stv_369367581586 ...

848 points, 5 cameras, 0 -> 0 event-run points
[082/183] stv_369368019182 ...

1534 points, 4 cameras, 0 -> 0 event-run points
[083/183] stv_369368247238 ...

827 points, 5 cameras, 70 -> 74 event-run points
[084/183] stv_369368258528 ...

910 points, 5 cameras, 44 -> 46 event-run points
[085/183] stv_377957568806 ...

2530 points, 8 cameras, 0 -> 0 event-run points
[086/183] stv_377958270645 ...

1919 points, 8 cameras, 0 -> 0 event-run points
[087/183] stv_386547180047 ...

1173 points, 7 cameras, 8 -> 8 event-run points
[088/183] stv_386547548488 ...

1195 points, 4 cameras, 61 -> 77 event-run points
[089/183] stv_386547633180 ...

1414 points, 7 cameras, 60 -> 74 event-run points
[090/183] stv_386547717669 ...

1030 points, 5 cameras, 108 -> 113 event-run points
[091/183] stv_395137147332 ...

837 points, 4 cameras, 35 -> 35 event-run points
[092/183] stv_395137530106 ...

1650 points, 9 cameras, 10 -> 9 event-run points
[093/183] stv_395137536331 ...

1963 points, 10 cameras, 235 -> 306 event-run points
[094/183] stv_395137575008 ...

1086 points, 3 cameras, 44 -> 44 event-run points
[095/183] stv_395138016907 ...

1301 points, 4 cameras, 0 -> 0 event-run points
[096/183] stv_403726945152 ...

2685 points, 10 cameras, 0 -> 0 event-run points
[097/183] stv_403727390848 ...

1114 points, 3 cameras, 3 -> 3 event-run points
[098/183] stv_403727411589 ...

1244 points, 4 cameras, 50 -> 57 event-run points
[099/183] stv_403727513981 ...

974 points, 6 cameras, 14 -> 15 event-run points
[100/183] stv_420907743111 ...

2707 points, 6 cameras, 54 -> 62 event-run points
[101/183] stv_420907788679 ...

1247 points, 3 cameras, 145 -> 182 event-run points
[102/183] stv_429497765184 ...

844 points, 4 cameras, 19 -> 21 event-run points
[103/183] stv_429497883105 ...

1221 points, 5 cameras, 0 -> 0 event-run points
[104/183] stv_42950519514 ...

1093 points, 5 cameras, 91 -> 123 event-run points
[105/183] stv_42950978749 ...

1151 points, 6 cameras, 11 -> 12 event-run points
[106/183] stv_438087432036 ...

1280 points, 3 cameras, 9 -> 15 event-run points
[107/183] stv_446676921101 ...

1338 points, 5 cameras, 48 -> 4 event-run points
[108/183] stv_446676962403 ...

908 points, 3 cameras, 31 -> 32 event-run points
[109/183] stv_446677119900 ...

1034 points, 3 cameras, 11 -> 12 event-run points
[110/183] stv_446677131304 ...

916 points, 3 cameras, 23 -> 27 event-run points
[111/183] stv_446677541838 ...

1474 points, 3 cameras, 320 -> 373 event-run points
[112/183] stv_455267146704 ...

1028 points, 5 cameras, 6 -> 6 event-run points
[113/183] stv_455267329115 ...

958 points, 3 cameras, 24 -> 26 event-run points
[114/183] stv_463856558214 ...

2594 points, 6 cameras, 381 -> 304 event-run points
[115/183] stv_463856750690 ...

1056 points, 3 cameras, 0 -> 0 event-run points
[116/183] stv_463857379909 ...

1156 points, 5 cameras, 17 -> 21 event-run points
[117/183] stv_463857647562 ...

1019 points, 3 cameras, 16 -> 15 event-run points
[118/183] stv_472446832201 ...

1327 points, 3 cameras, 75 -> 79 event-run points
[119/183] stv_481036586933 ...

1099 points, 3 cameras, 0 -> 0 event-run points
[120/183] stv_481036614501 ...

1159 points, 3 cameras, 0 -> 0 event-run points
[121/183] stv_481036753007 ...

2012 points, 6 cameras, 0 -> 0 event-run points
[122/183] stv_481036839646 ...

1279 points, 4 cameras, 45 -> 45 event-run points
[123/183] stv_489626538045 ...

986 points, 5 cameras, 87 -> 126 event-run points
[124/183] stv_489626566903 ...

1253 points, 4 cameras, 121 -> 121 event-run points
[125/183] stv_489626771138 ...

891 points, 6 cameras, 0 -> 0 event-run points
[126/183] stv_489627249934 ...

1167 points, 4 cameras, 0 -> 0 event-run points
[127/183] stv_498216222923 ...

1100 points, 3 cameras, 19 -> 21 event-run points
[128/183] stv_498217396542 ...

1166 points, 3 cameras, 0 -> 0 event-run points
[129/183] stv_515396131751 ...

915 points, 4 cameras, 25 -> 26 event-run points
[130/183] stv_515396303780 ...

1928 points, 9 cameras, 0 -> 0 event-run points
[131/183] stv_515396599194 ...

838 points, 6 cameras, 0 -> 0 event-run points
[132/183] stv_515396665634 ...

944 points, 6 cameras, 0 -> 0 event-run points
[133/183] stv_523986354332 ...

707 points, 4 cameras, 33 -> 33 event-run points
[134/183] stv_523987067704 ...

1244 points, 4 cameras, 58 -> 59 event-run points
[135/183] stv_532576054353 ...

2272 points, 6 cameras, 0 -> 0 event-run points
[136/183] stv_532576256705 ...

1180 points, 3 cameras, 171 -> 171 event-run points
[137/183] stv_532577049495 ...

949 points, 5 cameras, 4 -> 4 event-run points
[138/183] stv_541166181486 ...

1694 points, 8 cameras, 52 -> 75 event-run points
[139/183] stv_541166856332 ...

2329 points, 6 cameras, 153 -> 162 event-run points
[140/183] stv_541166985810 ...

1535 points, 3 cameras, 9 -> 12 event-run points
[141/183] stv_549755992463 ...

1099 points, 3 cameras, 17 -> 17 event-run points
[142/183] stv_549756627168 ...

1050 points, 5 cameras, 83 -> 83 event-run points
[143/183] stv_549756696622 ...

1115 points, 6 cameras, 151 -> 146 event-run points
[144/183] stv_558346776813 ...

916 points, 6 cameras, 0 -> 0 event-run points
[145/183] stv_558346808431 ...

1218 points, 4 cameras, 0 -> 0 event-run points
[146/183] stv_566936725849 ...

1299 points, 4 cameras, 55 -> 66 event-run points
[147/183] stv_566936751170 ...

1039 points, 3 cameras, 0 -> 0 event-run points
[148/183] stv_566936811310 ...

2134 points, 6 cameras, 2 -> 4 event-run points
[149/183] stv_584116028406 ...

1089 points, 5 cameras, 30 -> 36 event-run points
[150/183] stv_592705518006 ...

1398 points, 3 cameras, 0 -> 0 event-run points
[151/183] stv_592705538522 ...

1617 points, 4 cameras, 30 -> 30 event-run points
[152/183] stv_601295730966 ...

1319 points, 3 cameras, 219 -> 237 event-run points
[153/183] stv_601295761416 ...

1174 points, 3 cameras, 19 -> 19 event-run points
[154/183] stv_601296234211 ...

1708 points, 4 cameras, 0 -> 0 event-run points
[155/183] stv_60130127364 ...

717 points, 2 cameras, 0 -> 0 event-run points
[156/183] stv_60130131403 ...

1769 points, 4 cameras, 0 -> 0 event-run points
[157/183] stv_60130141761 ...

1065 points, 4 cameras, 45 -> 56 event-run points
[158/183] stv_609885850038 ...

807 points, 3 cameras, 185 -> 205 event-run points
[159/183] stv_609885930304 ...

2543 points, 6 cameras, 0 -> 0 event-run points
[160/183] stv_609885931971 ...

1210 points, 3 cameras, 30 -> 36 event-run points
[161/183] stv_618475663505 ...

1248 points, 3 cameras, 0 -> 0 event-run points
[162/183] stv_627065319105 ...

3408 points, 8 cameras, 125 -> 826 event-run points
[163/183] stv_627065796369 ...

1182 points, 3 cameras, 0 -> 0 event-run points
[164/183] stv_635655213015 ...

1187 points, 3 cameras, 296 -> 320 event-run points
[165/183] stv_635655520796 ...

1262 points, 3 cameras, 218 -> 219 event-run points
[166/183] stv_635656028029 ...

1537 points, 4 cameras, 45 -> 57 event-run points
[167/183] stv_644245286164 ...

2475 points, 6 cameras, 0 -> 0 event-run points
[168/183] stv_644245359876 ...

1343 points, 3 cameras, 282 -> 282 event-run points
[169/183] stv_644245387906 ...

1292 points, 3 cameras, 0 -> 0 event-run points
[170/183] stv_652835553348 ...

879 points, 3 cameras, 6 -> 7 event-run points
[171/183] stv_652835964994 ...

1247 points, 3 cameras, 33 -> 36 event-run points
[172/183] stv_68719676517 ...

782 points, 2 cameras, 226 -> 231 event-run points
[173/183] stv_68720526392 ...

672 points, 3 cameras, 3 -> 3 event-run points
[174/183] stv_68720714610 ...

684 points, 2 cameras, 17 -> 19 event-run points
[175/183] stv_77309980503 ...

1282 points, 3 cameras, 0 -> 0 event-run points
[176/183] stv_85900740505 ...

461 points, 2 cameras, 18 -> 18 event-run points
[177/183] stv_8590244035 ...

748 points, 4 cameras, 61 -> 65 event-run points
[178/183] stv_8590787268 ...

1593 points, 7 cameras, 86 -> 86 event-run points
[179/183] stv_8591170248 ...

819 points, 9 cameras, 90 -> 116 event-run points
[180/183] stv_8591303502 ...

1327 points, 5 cameras, 12 -> 12 event-run points
[181/183] stv_94489437356 ...

650 points, 3 cameras, 85 -> 85 event-run points
[182/183] stv_94489594805 ...

482 points, 2 cameras, 33 -> 35 event-run points
[183/183] stv_94489786439 ...

563 points, 5 cameras, 4 -> 4 event-run points

        candidates
status
ok             183

      candidates
band
g            183

       added_masked
count    183.000000
mean      50.912568
std       84.965300
min      -86.000000
25%        7.000000
50%       24.000000
75%       56.000000
max      684.000000

/Users/calder/code/malca/output/pdf/baseline_methods/diagnostics/reviewed_dippers/corroborated_mask_propagation_reviewed_dippers.pdf
/Users/calder/code/malca/output/pdf/baseline_methods/diagnostics/reviewed_dippers/corroborated_mask_propagation_reviewed_dippers.csv