# Baseline residual-comparison atlases

Generate the finalized five-panel baseline comparison for every reviewed dipper, LTV, and microlensing event in the July 1 Review database. Each baseline is scored independently by the production event detector, and each cohort is written as one multipage PDF.

In [1]:
import json
import re
from pathlib import Path
import sqlite3
import sys

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from astropy.coordinates import SkyCoord
from astropy.stats import biweight_location
import astropy.units as u
from IPython.display import display
from matplotlib.backends.backend_pdf import PdfPages

candidate_roots = [Path.cwd().resolve(), *Path.cwd().resolve().parents]
repo_root = next(
    (p for p in candidate_roots if (p / 'pyproject.toml').is_file() and (p / 'malca' / 'core' / 'baseline.py').is_file()),
    None,
)
if repo_root is None:
    raise RuntimeError(f'Could not find the MALCA repository above {Path.cwd()}')
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))

from malca.core.baseline import (
    global_median_baseline,
    per_camera_gp_baseline,
    per_camera_gp_baseline_masked,
)
from malca.core.utils import clean_lc
from malca.io.lightcurve_io import load_lightcurve_df, to_asassn_algorithm_frame
from malca.plotting.lightcurve_publication import FIG_SINGLE_COL_WIDTH, PUBLICATION_STYLE, finalize_publication_figure
from malca.review.native_lightcurve import resolve_lightcurve_path
from malca.review.store import get_candidate_payload
from malca.stv.events import DEFAULT_BASELINE_KWARGS, score_events_bayesian

JD_OFFSET = 2458000.0
RUN_ROOT = repo_root / 'output' / 'runs' / 'dat3-full-extended_2026-07-01-v4'
RUN_PARAMS = json.loads((RUN_ROOT / 'run_params.json').read_text())
REVIEW_DB = RUN_ROOT / 'review' / 'review.db'
BASE_OUTPUT_DIR = repo_root / 'output' / 'pdf' / 'baseline_methods' / 'main_comparison'
EVENT_CLASSES = {
    'dipper': {'label': 'Dippers', 'folder': 'reviewed_dippers'},
    'ltv': {'label': 'LTVs', 'folder': 'reviewed_ltvs'},
    'microlensing': {'label': 'Microlensing events', 'folder': 'reviewed_microlensing'},
}
CAMERA_PALETTE = (
    '#0072B2', '#009E73', '#56B4E9', '#6A3D9A', '#7F7F7F', '#E69F00',
    '#332288', '#44AA99', '#999933', '#8C6D31', '#333333', '#117733',
)

/opt/homebrew/Caskroom/miniconda/base/envs/malca/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
COHORT_SQL = """
SELECT c.candidate_id, c.asas_sn_id, c.asassn_var_name, c.ra, c.dec
FROM candidates AS c
INNER JOIN reviews AS r ON r.candidate_id = c.candidate_id
WHERE lower(trim(coalesce(r.event_class, ''))) = ?
ORDER BY c.candidate_id
"""

def cohort_output_paths(event_config):
    output_dir = BASE_OUTPUT_DIR / event_config['folder']
    output_dir.mkdir(parents=True, exist_ok=True)
    suffix = event_config['folder']
    return {
        'pdf': output_dir / f'baseline_main_comparison_{suffix}.pdf',
        'manifest': output_dir / 'baseline_main_comparison_manifest.csv',
    }

def load_reviewed_cohort(event_class):
    read_only_uri = f'file:{REVIEW_DB.as_posix()}?mode=ro'
    with sqlite3.connect(read_only_uri, uri=True) as connection:
        cohort = pd.read_sql_query(COHORT_SQL, connection, params=(event_class,))
        resolved_paths = []
        for candidate_id in cohort['candidate_id'].astype(str):
            payload = get_candidate_payload(connection, candidate_id)
            resolved = resolve_lightcurve_path(payload, RUN_ROOT)
            resolved_paths.append(str(resolved.resolve()) if resolved is not None else None)
    cohort['resolved_lightcurve_path'] = resolved_paths
    if cohort['candidate_id'].duplicated().any():
        raise AssertionError(f'Reviewed-{event_class} query returned duplicate candidate IDs.')
    return cohort

cohorts = {event_class: load_reviewed_cohort(event_class) for event_class in EVENT_CLASSES}
for event_class, event_config in EVENT_CLASSES.items():
    print(event_config['label'], len(cohorts[event_class]), cohort_output_paths(event_config)['pdf'])

Dippers 183 /Users/calder/code/malca/output/pdf/baseline_methods/main_comparison/reviewed_dippers/baseline_main_comparison_reviewed_dippers.pdf
LTVs 73 /Users/calder/code/malca/output/pdf/baseline_methods/main_comparison/reviewed_ltvs/baseline_main_comparison_reviewed_ltvs.pdf
Microlensing events 22 /Users/calder/code/malca/output/pdf/baseline_methods/main_comparison/reviewed_microlensing/baseline_main_comparison_reviewed_microlensing.pdf

In [3]:
def global_biweight_baseline(frame, *, c=6.0):
    result = frame.copy().reset_index(drop=True)
    mag = pd.to_numeric(result['mag'], errors='coerce').to_numpy(float)
    error = pd.to_numeric(result['error'], errors='coerce').to_numpy(float)
    finite = np.isfinite(mag)
    if not finite.any():
        raise ValueError('No finite magnitudes for the global biweight baseline.')
    center = float(biweight_location(mag[finite], c=c))
    result['baseline'] = center
    result['resid'] = mag - center
    residual = result['resid'].to_numpy(float)
    residual_finite = residual[np.isfinite(residual)]
    residual_median = float(np.median(residual_finite))
    scatter = float(1.4826 * np.median(np.abs(residual_finite - residual_median)))
    error_median = float(np.nanmedian(error[np.isfinite(error) & (error > 0)]))
    error_safe = np.where(np.isfinite(error) & (error > 0), error, error_median)
    robust_std = max(float(np.sqrt(scatter ** 2 + error_median ** 2)), 1e-6)
    result['sigma_resid'] = residual / robust_std
    result['sigma_eff'] = np.maximum(np.sqrt(error_safe ** 2 + scatter ** 2), 1e-6)
    result['baseline_source'] = 'global_biweight'
    return result

def select_best_band(cleaned):
    bands = pd.to_numeric(cleaned['v_g_band'], errors='coerce')
    counts = bands.value_counts()
    candidates = [band for band in (0.0, 1.0) if counts.get(band, 0) > 0]
    if not candidates:
        raise ValueError('No recognized g or V band observations.')
    band_value = max(candidates, key=lambda band: (int(counts.get(band, 0)), band == 0.0))
    return band_value, {0.0: 'g', 1.0: 'V'}[band_value]

EVENT_SCORING_KWARGS = {
    'p_points': int(RUN_PARAMS['p_points']),
    'mag_points': int(RUN_PARAMS['mag_points']),
    'trigger_mode': str(RUN_PARAMS['trigger_mode']),
    'significance_threshold': float(RUN_PARAMS['significance_threshold']),
    'run_min_points': int(RUN_PARAMS['run_min_points']),
    'max_gap_points': int(RUN_PARAMS['run_max_gap_points']),
    'run_max_gap_days': RUN_PARAMS['run_max_gap_days'],
    'run_min_duration_days': RUN_PARAMS['run_min_duration_days'],
    'compute_event_prob': True,
}

def production_event_mask(lightcurve, baseline_result):
    event_mask = np.zeros(len(lightcurve), dtype=bool)
    counts = {}
    for kind in ('dip', 'jump'):
        score = score_events_bayesian(
            lightcurve,
            kind=kind,
            baseline_func=None,
            df_base=baseline_result,
            logbf_threshold=float(RUN_PARAMS[f'logbf_threshold_{kind}']),
            **EVENT_SCORING_KWARGS,
        )
        indices = np.asarray(score['event_indices'], dtype=int)
        if indices.size:
            event_mask[indices] = True
        counts[kind] = int(indices.size)
    counts['either'] = int(event_mask.sum())
    return event_mask, counts

def prepare_candidate(candidate_row):
    path_value = candidate_row['resolved_lightcurve_path']
    if not path_value or not Path(path_value).is_file():
        raise FileNotFoundError(path_value)
    canonical = load_lightcurve_df(Path(path_value), apply_quality=True)
    cleaned = clean_lc(to_asassn_algorithm_frame(canonical)).reset_index(drop=True)
    band_value, band_label = select_best_band(cleaned)
    bands = pd.to_numeric(cleaned['v_g_band'], errors='coerce')
    lightcurve = cleaned.loc[np.isclose(bands, band_value)].copy().reset_index(drop=True)
    production = per_camera_gp_baseline_masked(lightcurve, **DEFAULT_BASELINE_KWARGS).reset_index(drop=True)
    baseline_results = {
        'Global median': global_median_baseline(lightcurve).reset_index(drop=True),
        'Global biweight': global_biweight_baseline(lightcurve),
        'Per-camera GP': per_camera_gp_baseline(lightcurve, **DEFAULT_BASELINE_KWARGS).reset_index(drop=True),
        'Masked per-camera GP': production,
    }
    event_masks = {}
    event_counts = {}
    for name, result in baseline_results.items():
        event_masks[name], event_counts[name] = production_event_mask(lightcurve, result)
    return lightcurve, band_label, production, baseline_results, event_masks, event_counts

In [4]:
def coordinate_label(candidate_row):
    catalog_name = candidate_row.get('asassn_var_name')
    if pd.notna(catalog_name):
        match = re.search(r'(J\d{6}(?:\.\d+)?[+-]\d{6}(?:\.\d+)?)', str(catalog_name))
        if match:
            return match.group(1)
    ra = pd.to_numeric(candidate_row.get('ra'), errors='coerce')
    dec = pd.to_numeric(candidate_row.get('dec'), errors='coerce')
    if np.isfinite(ra) and np.isfinite(dec):
        coord = SkyCoord(float(ra) * u.deg, float(dec) * u.deg)
        ra_text = coord.ra.to_string(unit=u.hourangle, sep='', precision=2, pad=True)
        dec_text = coord.dec.to_string(unit=u.deg, sep='', precision=1, pad=True, alwayssign=True)
        return f'J{ra_text}{dec_text}'
    return str(candidate_row['candidate_id']).removeprefix('stv_')

def camera_color_map(lightcurve):
    cameras = sorted(lightcurve['camera#'].dropna().unique(), key=str)
    return {camera: CAMERA_PALETTE[i % len(CAMERA_PALETTE)] for i, camera in enumerate(cameras)}

def plot_camera_points(ax, frame, y_col, camera_colors, *, masked_col=None):
    for camera, sub in frame.groupby('camera#', sort=True):
        sub = sub.sort_values('JD')
        x = sub['JD'].to_numpy(float) - JD_OFFSET
        ax.scatter(
            x, sub[y_col], s=5, alpha=1.0, color=camera_colors[camera],
            edgecolors='black', linewidths=0.18,
        )
        if masked_col is not None:
            masked = sub[masked_col].fillna(False).to_numpy(bool)
            if masked.any():
                ax.scatter(
                    x[masked], sub.loc[masked, y_col], s=13, marker='x',
                    color='#b2182b', linewidths=0.7, zorder=5,
                )

def make_comparison_figure(candidate_row, band_label, lightcurve, baseline_results, event_masks, *, figure_height=9.0):
    camera_colors = camera_color_map(lightcurve)
    with plt.rc_context(PUBLICATION_STYLE):
        fig, axes = plt.subplots(
            5, 1, figsize=(FIG_SINGLE_COL_WIDTH, float(figure_height)), sharex=True,
            gridspec_kw={'height_ratios': [1, 1, 1, 1, 1]},
        )
        residual_values = np.concatenate([
            pd.to_numeric(result['resid'], errors='coerce').to_numpy(float)
            for result in baseline_results.values()
        ])
        residual_values = residual_values[np.isfinite(residual_values)]
        raw_values = pd.to_numeric(lightcurve['mag'], errors='coerce').to_numpy(float)
        raw_values = raw_values[np.isfinite(raw_values)]
        raw_center = 0.5 * (float(np.min(raw_values)) + float(np.max(raw_values)))
        raw_half_span = 0.5 * (float(np.max(raw_values)) - float(np.min(raw_values))) * 1.05
        vertical_limit = max(0.15, float(np.max(np.abs(residual_values))) * 1.05, raw_half_span)

        plot_camera_points(axes[0], lightcurve, 'mag', camera_colors)
        axes[0].set_ylim(raw_center + vertical_limit, raw_center - vertical_limit)
        axes[0].set_ylabel(r'$m$ [mag]')
        axes[0].set_title('Raw', fontsize=8, pad=3)

        for ax, (name, result) in zip(axes[1:], baseline_results.items()):
            plot_frame = result.copy()
            plot_frame['event_mask'] = event_masks[name]
            plot_camera_points(ax, plot_frame, 'resid', camera_colors, masked_col='event_mask')
            ax.axhline(0, color='0.25', lw=0.7)
            ax.set_ylim(vertical_limit, -vertical_limit)
            ax.set_ylabel(r'$r$ [mag]')
            ax.set_title(name, fontsize=8, pad=3)

        axes[-1].set_xlabel('JD - 2458000')
        for ax in axes:
            ax.tick_params(direction='in', top=True, right=True)
        fig.suptitle(coordinate_label(candidate_row), fontsize=9)
        finalize_publication_figure(fig, rect=(0, 0, 1, 0.982))
        return fig

In [5]:
all_manifests = {}
failed_cohorts = []

for event_class, event_config in EVENT_CLASSES.items():
    cohort = cohorts[event_class]
    paths = cohort_output_paths(event_config)
    manifest_rows = []
    print(f"\nGenerating {event_config['label']} ({len(cohort)} candidates)")

    with PdfPages(paths['pdf']) as atlas_pdf:
        for position, (_, candidate_row) in enumerate(cohort.iterrows(), start=1):
            candidate_id = str(candidate_row['candidate_id'])
            print(f'[{position:03d}/{len(cohort):03d}] {candidate_id}', end=' ... ')
            try:
                lightcurve, band_label, production, baseline_results, event_masks, event_counts = prepare_candidate(candidate_row)
                fig = make_comparison_figure(candidate_row, band_label, lightcurve, baseline_results, event_masks)
                atlas_pdf.savefig(fig)
                plt.close(fig)
                sources = sorted(production['baseline_source'].dropna().astype(str).unique())
                manifest_rows.append({
                    'event_class': event_class,
                    'candidate_id': candidate_id,
                    'asas_sn_id': candidate_row.get('asas_sn_id'),
                    'lightcurve_path': candidate_row.get('resolved_lightcurve_path'),
                    'band': band_label,
                    'n_points': int(len(lightcurve)),
                    'n_cameras': int(lightcurve['camera#'].nunique()),
                    'n_event_global_median': event_counts['Global median']['either'],
                    'n_event_global_biweight': event_counts['Global biweight']['either'],
                    'n_event_per_camera_gp': event_counts['Per-camera GP']['either'],
                    'n_event_masked_per_camera_gp': event_counts['Masked per-camera GP']['either'],
                    'baseline_sources': ','.join(sources),
                    'status': 'ok',
                    'error': '',
                })
                print(f'{len(lightcurve)} points, {lightcurve["camera#"].nunique()} cameras, {band_label} band')
            except Exception as exc:
                manifest_rows.append({
                    'event_class': event_class,
                    'candidate_id': candidate_id,
                    'asas_sn_id': candidate_row.get('asas_sn_id'),
                    'lightcurve_path': candidate_row.get('resolved_lightcurve_path'),
                    'band': '',
                    'n_points': 0,
                    'n_cameras': 0,
                    'n_event_global_median': 0,
                    'n_event_global_biweight': 0,
                    'n_event_per_camera_gp': 0,
                    'n_event_masked_per_camera_gp': 0,
                    'baseline_sources': '',
                    'status': 'failed',
                    'error': f'{type(exc).__name__}: {exc}',
                })
                print(f'FAILED: {type(exc).__name__}: {exc}')

    manifest = pd.DataFrame(manifest_rows)
    manifest.to_csv(paths['manifest'], index=False)
    all_manifests[event_class] = manifest
    display(manifest['status'].value_counts().rename_axis('status').to_frame('candidates'))
    display(manifest.groupby('band').size().rename('candidates').to_frame())
    print(paths['pdf'])
    print(paths['manifest'])
    failures = manifest.loc[manifest['status'] != 'ok']
    if not failures.empty:
        display(failures)
        failed_cohorts.append((event_class, len(failures)))

if failed_cohorts:
    raise RuntimeError(f'Candidate failures remain: {failed_cohorts}')

Generating Dippers (183 candidates)
[001/183] stv_103079502524 ...

OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.

740 points, 2 cameras, g band
[002/183] stv_103080542701 ...

687 points, 2 cameras, g band
[003/183] stv_111669273145 ...

1514 points, 4 cameras, g band
[004/183] stv_111669291649 ...

1404 points, 4 cameras, g band
[005/183] stv_111669305159 ...

592 points, 2 cameras, g band
[006/183] stv_111669455609 ...

714 points, 2 cameras, g band
[007/183] stv_111669512802 ...

698 points, 5 cameras, g band
[008/183] stv_111669557747 ...

683 points, 2 cameras, g band
[009/183] stv_111670309173 ...

614 points, 4 cameras, g band
[010/183] stv_111670444883 ...

639 points, 4 cameras, g band
[011/183] stv_111670547411 ...

676 points, 2 cameras, g band
[012/183] stv_120259148405 ...

670 points, 2 cameras, g band
[013/183] stv_120259356690 ...

1114 points, 4 cameras, g band
[014/183] stv_120259384073 ...

645 points, 2 cameras, g band
[015/183] stv_120259975222 ...

701 points, 2 cameras, g band
[016/183] stv_128850429575 ...

794 points, 4 cameras, g band
[017/183] stv_137440061640 ...

986 points, 5 cameras, g band
[018/183] stv_146029052740 ...

632 points, 2 cameras, g band
[019/183] stv_146029419304 ...

954 points, 5 cameras, g band
[020/183] stv_146029595645 ...

558 points, 2 cameras, g band
[021/183] stv_154618944199 ...

938 points, 5 cameras, g band
[022/183] stv_154620038181 ...

987 points, 5 cameras, g band
[023/183] stv_163209415214 ...

1382 points, 8 cameras, g band
[024/183] stv_163209590869 ...

1066 points, 5 cameras, g band
[025/183] stv_171799189280 ...

1070 points, 5 cameras, g band
[026/183] stv_17180004254 ...

1196 points, 4 cameras, g band
[027/183] stv_17180374105 ...

983 points, 4 cameras, g band
[028/183] stv_17180437911 ...

1056 points, 3 cameras, g band
[029/183] stv_17181027305 ...

1409 points, 4 cameras, g band
[030/183] stv_180388640882 ...

1491 points, 7 cameras, g band
[031/183] stv_180388903123 ...

1099 points, 5 cameras, g band
[032/183] stv_188978596613 ...

1758 points, 11 cameras, g band
[033/183] stv_188979090903 ...

457 points, 5 cameras, g band
[034/183] stv_188979142258 ...

1694 points, 8 cameras, g band
[035/183] stv_197569146752 ...

1256 points, 5 cameras, g band
[036/183] stv_197569226514 ...

1011 points, 6 cameras, g band
[037/183] stv_197569238413 ...

1130 points, 5 cameras, g band
[038/183] stv_206158504352 ...

931 points, 5 cameras, g band
[039/183] stv_206158525635 ...

2018 points, 11 cameras, g band
[040/183] stv_214748665650 ...

643 points, 6 cameras, g band
[041/183] stv_214748985701 ...

1872 points, 11 cameras, g band
[042/183] stv_223338997633 ...

1052 points, 6 cameras, g band
[043/183] stv_240518568351 ...

589 points, 8 cameras, g band
[044/183] stv_240518636016 ...

1006 points, 5 cameras, g band
[045/183] stv_240518717560 ...

575 points, 5 cameras, g band
[046/183] stv_240519504803 ...

989 points, 5 cameras, g band
[047/183] stv_249109213616 ...

1224 points, 5 cameras, g band
[048/183] stv_25770235550 ...

1350 points, 5 cameras, g band
[049/183] stv_25770316308 ...

1310 points, 4 cameras, g band
[050/183] stv_25770384706 ...

1112 points, 3 cameras, g band
[051/183] stv_25771086021 ...

588 points, 2 cameras, g band
[052/183] stv_266288191401 ...

1272 points, 5 cameras, g band
[053/183] stv_266288257407 ...

1350 points, 7 cameras, g band
[054/183] stv_266288875581 ...

1887 points, 11 cameras, g band
[055/183] stv_266289132701 ...

1445 points, 4 cameras, g band
[056/183] stv_283467842509 ...

1153 points, 5 cameras, g band
[057/183] stv_283467971446 ...

946 points, 7 cameras, g band
[058/183] stv_283468165807 ...

1085 points, 3 cameras, g band
[059/183] stv_283468931829 ...

1073 points, 3 cameras, g band
[060/183] stv_292057989013 ...

1388 points, 6 cameras, g band
[061/183] stv_292059016008 ...

930 points, 5 cameras, g band
[062/183] stv_300648040390 ...

1115 points, 3 cameras, g band
[063/183] stv_300648087617 ...

1634 points, 6 cameras, g band
[064/183] stv_300648890329 ...

1022 points, 5 cameras, g band
[065/183] stv_309238625577 ...

1300 points, 5 cameras, g band
[066/183] stv_317828555902 ...

1754 points, 3 cameras, g band
[067/183] stv_317828613008 ...

1928 points, 7 cameras, g band
[068/183] stv_326417748428 ...

2284 points, 11 cameras, g band
[069/183] stv_326417838270 ...

1125 points, 5 cameras, g band
[070/183] stv_343598086600 ...

1459 points, 5 cameras, g band
[071/183] stv_34360122433 ...

1183 points, 4 cameras, g band
[072/183] stv_34360173609 ...

1150 points, 3 cameras, g band
[073/183] stv_352187778169 ...

934 points, 5 cameras, g band
[074/183] stv_352188453021 ...

1140 points, 3 cameras, g band
[075/183] stv_360777789109 ...

1121 points, 5 cameras, g band
[076/183] stv_360777826205 ...

1643 points, 5 cameras, g band
[077/183] stv_360778187147 ...

1365 points, 8 cameras, g band
[078/183] stv_369367234804 ...

1702 points, 7 cameras, g band
[079/183] stv_369367304600 ...

782 points, 5 cameras, g band
[080/183] stv_369367489518 ...

909 points, 5 cameras, g band
[081/183] stv_369367581586 ...

848 points, 5 cameras, g band
[082/183] stv_369368019182 ...

1534 points, 4 cameras, g band
[083/183] stv_369368247238 ...

827 points, 5 cameras, g band
[084/183] stv_369368258528 ...

910 points, 5 cameras, g band
[085/183] stv_377957568806 ...

2530 points, 8 cameras, g band
[086/183] stv_377958270645 ...

1919 points, 8 cameras, g band
[087/183] stv_386547180047 ...

1173 points, 7 cameras, g band
[088/183] stv_386547548488 ...

1195 points, 4 cameras, g band
[089/183] stv_386547633180 ...

1414 points, 7 cameras, g band
[090/183] stv_386547717669 ...

1030 points, 5 cameras, g band
[091/183] stv_395137147332 ...

837 points, 4 cameras, g band
[092/183] stv_395137530106 ...

1650 points, 9 cameras, g band
[093/183] stv_395137536331 ...

1963 points, 10 cameras, g band
[094/183] stv_395137575008 ...

1086 points, 3 cameras, g band
[095/183] stv_395138016907 ...

1301 points, 4 cameras, g band
[096/183] stv_403726945152 ...

2685 points, 10 cameras, g band
[097/183] stv_403727390848 ...

1114 points, 3 cameras, g band
[098/183] stv_403727411589 ...

1244 points, 4 cameras, g band
[099/183] stv_403727513981 ...

974 points, 6 cameras, g band
[100/183] stv_420907743111 ...

2707 points, 6 cameras, g band
[101/183] stv_420907788679 ...

1247 points, 3 cameras, g band
[102/183] stv_429497765184 ...

844 points, 4 cameras, g band
[103/183] stv_429497883105 ...

1221 points, 5 cameras, g band
[104/183] stv_42950519514 ...

1093 points, 5 cameras, g band
[105/183] stv_42950978749 ...

1151 points, 6 cameras, g band
[106/183] stv_438087432036 ...

1280 points, 3 cameras, g band
[107/183] stv_446676921101 ...

1338 points, 5 cameras, g band
[108/183] stv_446676962403 ...

908 points, 3 cameras, g band
[109/183] stv_446677119900 ...

1034 points, 3 cameras, g band
[110/183] stv_446677131304 ...

916 points, 3 cameras, g band
[111/183] stv_446677541838 ...

1474 points, 3 cameras, g band
[112/183] stv_455267146704 ...

1028 points, 5 cameras, g band
[113/183] stv_455267329115 ...

958 points, 3 cameras, g band
[114/183] stv_463856558214 ...

2594 points, 6 cameras, g band
[115/183] stv_463856750690 ...

1056 points, 3 cameras, g band
[116/183] stv_463857379909 ...

1156 points, 5 cameras, g band
[117/183] stv_463857647562 ...

1019 points, 3 cameras, g band
[118/183] stv_472446832201 ...

1327 points, 3 cameras, g band
[119/183] stv_481036586933 ...

1099 points, 3 cameras, g band
[120/183] stv_481036614501 ...

1159 points, 3 cameras, g band
[121/183] stv_481036753007 ...

2012 points, 6 cameras, g band
[122/183] stv_481036839646 ...

1279 points, 4 cameras, g band
[123/183] stv_489626538045 ...

986 points, 5 cameras, g band
[124/183] stv_489626566903 ...

1253 points, 4 cameras, g band
[125/183] stv_489626771138 ...

891 points, 6 cameras, g band
[126/183] stv_489627249934 ...

1167 points, 4 cameras, g band
[127/183] stv_498216222923 ...

1100 points, 3 cameras, g band
[128/183] stv_498217396542 ...

1166 points, 3 cameras, g band
[129/183] stv_515396131751 ...

915 points, 4 cameras, g band
[130/183] stv_515396303780 ...

1928 points, 9 cameras, g band
[131/183] stv_515396599194 ...

838 points, 6 cameras, g band
[132/183] stv_515396665634 ...

944 points, 6 cameras, g band
[133/183] stv_523986354332 ...

707 points, 4 cameras, g band
[134/183] stv_523987067704 ...

1244 points, 4 cameras, g band
[135/183] stv_532576054353 ...

2272 points, 6 cameras, g band
[136/183] stv_532576256705 ...

1180 points, 3 cameras, g band
[137/183] stv_532577049495 ...

949 points, 5 cameras, g band
[138/183] stv_541166181486 ...

1694 points, 8 cameras, g band
[139/183] stv_541166856332 ...

2329 points, 6 cameras, g band
[140/183] stv_541166985810 ...

1535 points, 3 cameras, g band
[141/183] stv_549755992463 ...

1099 points, 3 cameras, g band
[142/183] stv_549756627168 ...

1050 points, 5 cameras, g band
[143/183] stv_549756696622 ...

1115 points, 6 cameras, g band
[144/183] stv_558346776813 ...

916 points, 6 cameras, g band
[145/183] stv_558346808431 ...

1218 points, 4 cameras, g band
[146/183] stv_566936725849 ...

1299 points, 4 cameras, g band
[147/183] stv_566936751170 ...

1039 points, 3 cameras, g band
[148/183] stv_566936811310 ...

2134 points, 6 cameras, g band
[149/183] stv_584116028406 ...

1089 points, 5 cameras, g band
[150/183] stv_592705518006 ...

1398 points, 3 cameras, g band
[151/183] stv_592705538522 ...

1617 points, 4 cameras, g band
[152/183] stv_601295730966 ...

1319 points, 3 cameras, g band
[153/183] stv_601295761416 ...

1174 points, 3 cameras, g band
[154/183] stv_601296234211 ...

1708 points, 4 cameras, g band
[155/183] stv_60130127364 ...

717 points, 2 cameras, g band
[156/183] stv_60130131403 ...

1769 points, 4 cameras, g band
[157/183] stv_60130141761 ...

1065 points, 4 cameras, g band
[158/183] stv_609885850038 ...

807 points, 3 cameras, g band
[159/183] stv_609885930304 ...

2543 points, 6 cameras, g band
[160/183] stv_609885931971 ...

1210 points, 3 cameras, g band
[161/183] stv_618475663505 ...

1248 points, 3 cameras, g band
[162/183] stv_627065319105 ...

3408 points, 8 cameras, g band
[163/183] stv_627065796369 ...

1182 points, 3 cameras, g band
[164/183] stv_635655213015 ...

1187 points, 3 cameras, g band
[165/183] stv_635655520796 ...

1262 points, 3 cameras, g band
[166/183] stv_635656028029 ...

1537 points, 4 cameras, g band
[167/183] stv_644245286164 ...

2475 points, 6 cameras, g band
[168/183] stv_644245359876 ...

1343 points, 3 cameras, g band
[169/183] stv_644245387906 ...

1292 points, 3 cameras, g band
[170/183] stv_652835553348 ...

879 points, 3 cameras, g band
[171/183] stv_652835964994 ...

1247 points, 3 cameras, g band
[172/183] stv_68719676517 ...

782 points, 2 cameras, g band
[173/183] stv_68720526392 ...

672 points, 3 cameras, g band
[174/183] stv_68720714610 ...

684 points, 2 cameras, g band
[175/183] stv_77309980503 ...

1282 points, 3 cameras, g band
[176/183] stv_85900740505 ...

461 points, 2 cameras, g band
[177/183] stv_8590244035 ...

748 points, 4 cameras, g band
[178/183] stv_8590787268 ...

1593 points, 7 cameras, g band
[179/183] stv_8591170248 ...

819 points, 9 cameras, g band
[180/183] stv_8591303502 ...

1327 points, 5 cameras, g band
[181/183] stv_94489437356 ...

650 points, 3 cameras, g band
[182/183] stv_94489594805 ...

482 points, 2 cameras, g band
[183/183] stv_94489786439 ...

563 points, 5 cameras, g band

        candidates
status
ok             183

      candidates
band
g            183

/Users/calder/code/malca/output/pdf/baseline_methods/main_comparison/reviewed_dippers/baseline_main_comparison_reviewed_dippers.pdf
/Users/calder/code/malca/output/pdf/baseline_methods/main_comparison/reviewed_dippers/baseline_main_comparison_manifest.csv

Generating LTVs (73 candidates)
[001/073] stv_103079592305 ...

1219 points, 5 cameras, g band
[002/073] stv_103079650484 ...

1629 points, 7 cameras, g band
[003/073] stv_103079950092 ...

599 points, 4 cameras, g band
[004/073] stv_111670044507 ...

316 points, 1 cameras, V band
[005/073] stv_111670620905 ...

356 points, 2 cameras, V band
[006/073] stv_137439054289 ...

579 points, 3 cameras, g band
[007/073] stv_137439477603 ...

589 points, 2 cameras, g band
[008/073] stv_137440154906 ...

1467 points, 9 cameras, g band
[009/073] stv_137440201308 ...

644 points, 2 cameras, g band
[010/073] stv_146030077569 ...

710 points, 4 cameras, g band
[011/073] stv_163208960826 ...

734 points, 2 cameras, g band
[012/073] stv_163209477162 ...

1243 points, 8 cameras, g band
[013/073] stv_163209716952 ...

2304 points, 6 cameras, g band
[014/073] stv_171798780416 ...

811 points, 5 cameras, g band
[015/073] stv_171799145104 ...

1801 points, 9 cameras, g band
[016/073] stv_171799642000 ...

1805 points, 9 cameras, g band
[017/073] stv_188979037909 ...

163 points, 4 cameras, g band
[018/073] stv_206159573408 ...

1277 points, 5 cameras, g band
[019/073] stv_214748792627 ...

1481 points, 9 cameras, g band
[020/073] stv_214749434145 ...

1075 points, 5 cameras, g band
[021/073] stv_223339033515 ...

1358 points, 8 cameras, g band
[022/073] stv_249108767924 ...

1434 points, 7 cameras, g band
[023/073] stv_257698583972 ...

2092 points, 10 cameras, g band
[024/073] stv_257698611829 ...

1321 points, 9 cameras, g band
[025/073] stv_25770935107 ...

690 points, 4 cameras, g band
[026/073] stv_274879061545 ...

1040 points, 4 cameras, g band
[027/073] stv_283467848623 ...

916 points, 5 cameras, g band
[028/073] stv_283468840553 ...

814 points, 5 cameras, g band
[029/073] stv_292058271348 ...

1338 points, 6 cameras, g band
[030/073] stv_300648281213 ...

1217 points, 5 cameras, g band
[031/073] stv_326418666413 ...

934 points, 5 cameras, g band
[032/073] stv_326418682923 ...

1000 points, 5 cameras, g band
[033/073] stv_335007785809 ...

1104 points, 5 cameras, g band
[034/073] stv_343598407644 ...

1350 points, 5 cameras, g band
[035/073] stv_34360526644 ...

409 points, 3 cameras, g band
[036/073] stv_34360872825 ...

903 points, 4 cameras, g band
[037/073] stv_360777393829 ...

1019 points, 5 cameras, g band
[038/073] stv_360778012958 ...

876 points, 4 cameras, g band
[039/073] stv_377958107056 ...

2658 points, 6 cameras, g band
[040/073] stv_412317792480 ...

1837 points, 4 cameras, g band
[041/073] stv_463857262651 ...

1156 points, 4 cameras, g band
[042/073] stv_472447294641 ...

1168 points, 3 cameras, g band
[043/073] stv_481037430439 ...

1221 points, 5 cameras, g band
[044/073] stv_489627306501 ...

1030 points, 2 cameras, g band
[045/073] stv_506806594991 ...

699 points, 3 cameras, g band
[046/073] stv_506806749243 ...

994 points, 5 cameras, g band
[047/073] stv_515396829084 ...

1692 points, 6 cameras, g band
[048/073] stv_523986746107 ...

2027 points, 5 cameras, g band
[049/073] stv_523986833778 ...

1238 points, 4 cameras, g band
[050/073] stv_532576812012 ...

1561 points, 3 cameras, g band
[051/073] stv_541165922228 ...

1201 points, 3 cameras, g band
[052/073] stv_541166608494 ...

1804 points, 5 cameras, g band
[053/073] stv_558346040167 ...

1733 points, 4 cameras, g band
[054/073] stv_558346776005 ...

935 points, 6 cameras, g band
[055/073] stv_592705976149 ...

2341 points, 6 cameras, g band
[056/073] stv_601295818531 ...

1484 points, 3 cameras, g band
[057/073] stv_601296397329 ...

1562 points, 3 cameras, g band
[058/073] stv_60130665647 ...

657 points, 5 cameras, g band
[059/073] stv_609885936232 ...

2440 points, 6 cameras, g band
[060/073] stv_618475508303 ...

2383 points, 6 cameras, g band
[061/073] stv_618475857882 ...

2664 points, 6 cameras, g band
[062/073] stv_618475870508 ...

2447 points, 5 cameras, g band
[063/073] stv_618476031047 ...

2559 points, 6 cameras, g band
[064/073] stv_635655625971 ...

1196 points, 3 cameras, g band
[065/073] stv_635655781016 ...

2297 points, 4 cameras, g band
[066/073] stv_644246078041 ...

640 points, 2 cameras, g band
[067/073] stv_68720439057 ...

753 points, 4 cameras, g band
[068/073] stv_77309467421 ...

691 points, 2 cameras, V band
[069/073] stv_85900222044 ...

809 points, 2 cameras, g band
[070/073] stv_85900768138 ...

666 points, 2 cameras, g band
[071/073] stv_8590719241 ...

1690 points, 8 cameras, g band
[072/073] stv_8590729684 ...

622 points, 4 cameras, g band
[073/073] stv_8591337868 ...

1016 points, 4 cameras, g band

        candidates
status
ok              73

      candidates
band
V              3
g             70

/Users/calder/code/malca/output/pdf/baseline_methods/main_comparison/reviewed_ltvs/baseline_main_comparison_reviewed_ltvs.pdf
/Users/calder/code/malca/output/pdf/baseline_methods/main_comparison/reviewed_ltvs/baseline_main_comparison_manifest.csv

Generating Microlensing events (22 candidates)
[001/022] stv_103079263205 ...

677 points, 2 cameras, g band
[002/022] stv_111669286812 ...

702 points, 2 cameras, g band
[003/022] stv_120259784233 ...

474 points, 2 cameras, g band
[004/022] stv_171799355659 ...

788 points, 5 cameras, g band
[005/022] stv_188979054063 ...

1045 points, 7 cameras, g band
[006/022] stv_206158789308 ...

572 points, 2 cameras, g band
[007/022] stv_257698235806 ...

1963 points, 6 cameras, g band
[008/022] stv_326418117943 ...

857 points, 5 cameras, g band
[009/022] stv_34360800532 ...

647 points, 2 cameras, g band
[010/022] stv_489626721133 ...

920 points, 5 cameras, g band
[011/022] stv_523987093059 ...

1182 points, 3 cameras, g band
[012/022] stv_532576740522 ...

1399 points, 3 cameras, g band
[013/022] stv_541166175153 ...

1064 points, 4 cameras, g band
[014/022] stv_566936418537 ...

2332 points, 6 cameras, g band
[015/022] stv_566936429516 ...

1397 points, 3 cameras, g band
[016/022] stv_575525833425 ...

1169 points, 3 cameras, g band
[017/022] stv_609886176748 ...

1239 points, 3 cameras, g band
[018/022] stv_618475317371 ...

1898 points, 5 cameras, g band
[019/022] stv_627065322644 ...

1621 points, 4 cameras, g band
[020/022] stv_652835365414 ...

1147 points, 3 cameras, g band
[021/022] stv_68720699238 ...

620 points, 2 cameras, g band
[022/022] stv_77309955721 ...

705 points, 2 cameras, g band

        candidates
status
ok              22

      candidates
band
g             22

/Users/calder/code/malca/output/pdf/baseline_methods/main_comparison/reviewed_microlensing/baseline_main_comparison_reviewed_microlensing.pdf
/Users/calder/code/malca/output/pdf/baseline_methods/main_comparison/reviewed_microlensing/baseline_main_comparison_manifest.csv